### ISSUE TITLE
[Issue]: Input box strange behavior with hotkey for increasing and decreasing strength

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#1115]
### Issue Description

Normal behavior is that when the user includes in a prompt something like: "<lora:PixelArt-skyatmoon:1>", if they press CTRL+UP or DOWN the strength will increase and decrease by a specified amount. In my setup, that is "0.1" instead of the usual "0.05".

On the current build, if the caret is positioned inside the <>, behavior is normal. If the caret is positioned right after the >, then the effect is: "<lora:PixelArt-skyatmoon:0.(9>:1.1)". This is a new wrong behavior on my setup at least.

### Version Platform Description

2023-05-21
hash: 26b05ef8

**Comment by vladmandic** [comment]
if you position cursor just after `>` and use ctrl+up/down, there is no good logic. simple solution is as you've noted yourself - select term you want to modify and then ctrl+up/down works.

i get what you're saying and yes, in theory anything is doable, even your case (although technically incorrect, but does work), but on a list of priorities, this would be really low. your choice if you want to keep issue open and find someone to do a pr (with full testing since prompt parsing is messy at best).

**Comment by vladmandic** [comment]
btw, note that using strength **inside** extra network without using additional set of `()` is pretty much invalid to start with.
for example: `<lora:name:0.5>` - is 0.5 a strength for name or is it extra network param that should be parsed by lora extra network? here's an example of extra network params `<lyco:name:unet=0.5:dyn=13>`

how to acount for that when using ctrl+up/down? i don't even want to start.
