### ISSUE TITLE
[Issue]: Image generation progress display in the console is inconsistent

### ISSUE THREAD

**Issue by VictorZakharov** [vladmandic/automatic#1178]
### Issue Description

It starts giving progress in a very cool way, showing the init stage and then it/sec, but then switches to A1111 default style.

![image](https://github.com/vladmandic/automatic/assets/8978766/51d9b82a-8195-49f6-a4a6-a51e194af910)

Expected: should stick to one style.

### Version Platform Description

OS: Windows 10.
GPU: 4070 Ti
Version: 8022de74 Fri May 26 23:43:37 2023 +0300

**Comment by vladmandic** [comment]
you didn't say what you're doing. but most likely you're doing something that triggers both txt2img and img2img (for example txt2img + hires or something like that). and each uses its own sampler - only default sampler has been updated to new style because its part of this repo. all other samplers are external and cannot be updated.
to check which sampler you're using for second stage, go to settings -> sampler parameters.

and sorry, but this is not an issue no matter how you look at it.
at best it would be a feature request, but given that external samplers cannot be styled, its not even that.

**Comment by VictorZakharov** [comment]
@vladmandic I did txt2img, default args. Then I changed sampler to Euler A.

Didn't realize that progress is sampler dependent. Makes no sense to me, because all samplers have the same progress. So if each progress bar is implemented directly in the sampler, it's code duplication. And they all do the same thing at the end.

Looks like a bunch of tech debt all around.

**Comment by vladmandic** [comment]
yes, that is correct. and i'd be ok with changing that except that only unipc sampler actually lives in this repo, all other samplers are in upstream packages - so if i start editing them, i cant stay in-sync anymore that easily.

**Comment by VictorZakharov** [comment]
@vladmandic Is there a way to redirect output from samplers, parse it out and display new progress instead?

**Comment by vladmandic** [comment]
that not really as progress bar output contains control sequences which are specific to current terminal capabilities. if it gets redirected anywhere, it doesn't know what a "color" is anymore.

it is possible to monkey-patch python code in memory, but i'm reluctant to do that for a small visual gain as it does introduce risks.

for example in `modules/sd_samplers_kdiffusion.py` add lines at the end
```python
from tqdm.rich import trange
k_diffusion.sampling.trange = trange
```
and it will patch (partially only, not will full style, but its a step) euler a and some others.

**Comment by VictorZakharov** [comment]
@vladmandic I thought the default output is black/white, so there is no color to lose.

**Comment by vladmandic** [comment]
i just used colors as example. even just moving cursor left/right is a control sequence - and you need that to change the text of counter which is printed.
