### ISSUE TITLE
[Feature]: CFG Rescale

### ISSUE THREAD

**Issue by Metal079** [vladmandic/automatic#1186]
### Feature description

Theres a an branch of auto1111 that has cfg rescale, I think it would be a great addition seeing as im sure many models will be implementing the changes from here https://arxiv.org/abs/2305.08891 when training models. CFG rescale is also needed to take full advantage of these models.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/cfg-rescale

**Comment by vladmandic** [comment]
cfg rescale is coming soon, but its nearly identical to what's already here - dynamic cfg.

**Comment by zslittlehelper** [comment]
After trying the rescaler (in Auto1111), it seems to add a lot of detail to my generations that I can't recreate with dynamic cfg (even after fiddling with the scale schedulers). So, here's another (pleading) vote to implement this.

**Comment by drhead** [comment]
*Admittedly not as a user of this fork*, but asking on behalf of some of the people testing our models who are users of your fork, I would request adding this sooner if possible.  I and a few others are working on models implementing those changes and even early on in the training process, well before the loss has settled since switching to V-loss I can tell you definitively that CFG rescale does work VERY differently from how it works on normal models.

Normal models using CFG rescale will desaturate as in the example from A1111's pull request.  On one of the models we are testing, the effect is quite different:

![image](https://github.com/vladmandic/automatic/assets/1313496/c402f3da-c009-479d-b977-d2f08873536f)
![image](https://github.com/vladmandic/automatic/assets/1313496/ce6ec58e-63ca-4c36-b398-9f6d11ecbe71)

You can notice that saturation is not reduced as in A1111's example in his pull request:

![image](https://github.com/vladmandic/automatic/assets/1313496/3f87a362-f0b8-4888-b6fd-8b54257c8437)

and instead, saturation is very consistently at a reasonable value.  The value of 0.7 is calibrated for when terminal SNR is zero.  Full disclosure, I believe I may have not produced these grids with beta rescaling applied.  It is also worth noting that the pull request in the A1111 repo only applies to K-diffusion samplers and that there is a working implementation of it for DDIM in the Huggingface Diffusers repo.

If you want to fully implement the paper (which I *highly* recommend doing, since I have already discovered ways that these fixes have improved models beyond what the authors stated, most notably so far improved inpainting performance), there are two other things that need to be added for full performance.  The first is changing LDM samplers to use trailing timesteps instead of leading (K-diffusion samplers do not need to be changed, they already use linspace which is just about as good, unknown if they would be better off on trailing or not).  The second is applying the beta rescale described in the paper on inference with the DDIM sampler.  The first one should be an unambiguous quality increase from my testing, the second one can only be safely applied to models using V-prediction and will result in solid black images otherwise (do NOT assume that any model with V-prediction must be 2.0 based, I have seen other codebases (namely Kohya) include warnings to that effect.  Retraining on V-prediction is not terribly time consuming all things considered and works fine on 1.5, which is what the images I just showed you are from).  

K-diffusion hijacks LDM's beta schedule and will malfunction if allowed to hijack the beta schedule that is rescaled to zero terminal SNR per the method described in the paper.  I don't know how to modify K-diffusion to enforce zero SNR at the last timestep, but things work fine without zero SNR at the last timestep although they are clearly better with it on an appropriate model.  It would still be nice to be able to at least use it in DDIM.

**Comment by vladmandic** [comment]
@drhead very good info, thanks.
btw, if there is code that is applicable to ddim, it can probably be applied (with modifications) to unipc as well.

**Comment by vladmandic** [comment]
instead of rescale, we now have new setting - cfg end. so you can still use rescale in diffusers, but you can augment settings to (for example) use high cfg scale to start with and have early-end so it doesn't overbake the image.
