### ISSUE TITLE
[Issue]: Recent update broke ".txt" copying on "save"

### ISSUE THREAD

**Issue by Razunter** [vladmandic/automatic#1208]
### Issue Description

Usually .txt gets copied to save directory with the image, a recent update broke this behavior, only the image gets copied now.
Txt generated by "Create a text file next to every image with generation parameters" option.

```
00:36:50-750303 INFO     Copying image: D:\Soft\StableDiffusion-Automatic1111-fork\outputs\text\2023-05-30\install
                         shield wizard holding a diskette 1 3\00005-1.5_custom_dreamshaper_6BakedVae-3200048260.webp ->
                         D:\Soft\StableDiffusion-Automatic1111-fork\outputs/save
```
### Version Platform Description

00:29:35-926069 INFO     Python 3.10.11 on Windows
00:29:36-030349 INFO     Version: 8354b7c6 Mon May 29 15:42:24 2023 -0400

**Comment by vladmandic** [comment]
not broken, thats by design. when txt is selected to be saved, its saved with original image. save button now makes a fast copy of image instead of processing it again. yes, it may break your workflow, but there really is not reason to have two copies of txt.
if original image was never auto-saved, save button will process it as usual.

**Comment by Razunter** [comment]
Hm. Same version. Tried disabling "Always save all generated images". TXT still isn't saved and now it ignores extension in settings (webp), saves as png, and also saves with temporary file name instead of filename pattern.

**Comment by vladmandic** [comment]
ah, needed to exclude temp files from fast-copy concept. fixed.
