### ISSUE TITLE
[Issue]: Error running git: None / submodule

### ISSUE THREAD

**Issue by radry** [vladmandic/automatic#1214]
### Issue Description

I'm starting webui with following arguments "--upgrade --skip-extensions --autolaunch"
(I manually update the extensions from within webui afterwards, so they should be up to date)

Whenever I launch it and it tries to update I get the message:
`Error running git: None / submodule`  

However, the UI starts and works normally.
When relaunching the server, the error doesn't appear, since it doesn't try to update again.

Git is installed and works fine on its own. This issue appeared sometime in the past 3 weeks. Before it never occured.

**Full log:**
[webui.log](https://github.com/vladmandic/automatic/files/11598643/webui.log)

### Version Platform Description

Version: 8354b7c6 Mon May 29 15:42:24 2023 -0400

Windows 10

**Comment by vladmandic** [comment]
annoying, but pretty much cosmetic only issue.
the root cause is that git keeps local cache and few weeks ago i've simplified this repo and removed some of the non-necessary built-in extensions. for new git clones, this would not happen. but for old installs, git checks status of everything still in cache and it cannot find it anymore in the repo:

> fatal: no submodule mapping found in .gitmodules for path 'extensions-builtin/sd-extension-aesthetic-scorer'

cleaning up git cache is pretty complicated so i suggest to either ignore this error or perform a clean install.
