### ISSUE TITLE
[Feature]: UI Request Model Manager

### ISSUE THREAD

**Issue by DirtyHamster** [vladmandic/automatic#1297]
### Feature description

The basic idea is that many of the models come with suggested vae's and sometimes negative prompts as well. So I'd suggest something that would help index them that is more organizable.

Basic fields would be similar to:
Model name:
Style description:
Model pic:
Tag cloud: things like photorealistic, anime, 2D, 3D, game like.... (This would be the searchable tag)

loads corresponding "Model"
loads corresponding "Vae"
loads corresponding "default negative embeddings", these seem to be getting more popular.
loads corresponding "other substitutional portions" , other portions can be swapped out but it's kind of fringe.

Use existing config: like use index 1

This would be a substitute load so you don't have to load everything individually.

**Comment by vladmandic** [comment]
silly question - who would fill all those fields?
i don't want to have core app integrating with external services like civit.ai, that's for extensions to do.
i fear that having all-mighty model manager would very quickly degrade.

**Comment by DrJKL** [comment]
Something like https://github.com/rifeWithKaiju/model_preset_manager ?

**Comment by Aptronymist** [comment]
> Something like [rifeWithKaiju/model_preset_manager](https://github.com/rifeWithKaiju/model_preset_manager) ?

I was just going to suggest that myself, though I haven't actually used it yet, it's installed and on my list for today. Civitai Helper for example DOES scrape individual model pages for info, including things like activation keywords, so I don't see why that code couldn't be ganked and repurposed to try to pick out suggested negative prompts and the like.
That being said, it would be a lot of scope creep to include that kind of thing as Vlad pointed out. I guess if you HAD the data already from another source it could be included, but Vlad clearly doesn't want to get in the business of scraping for it or creating a list like Model Keyword does.
Now that I think about it, maybe that should be a feature request sent to the model keyword extension since they clearly already do that kind of thing.

**Comment by vladmandic** [comment]
further work will be tracked under #800
