### ISSUE TITLE
[Issue]: Local change that aren't changed except from the repo itself

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#1320]
### Issue Description

I still get every now and then an error because of "unmerged" files that aren't touched by me:

From https://github.com/vladmandic/automatic
   9726b4d2..c0a824d8  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
        scripts/xyz_grid.py
Please commit your changes or stash them before you merge.
Aborting
Updating 9726b4d2..c0a824d8

The file in question (and that's mostly the case) is only handled by the repo itself, so why can this issue always come up?

### Version Platform Description

Win10, FF106
Version: 9726b4d2 Sun Jun 4 13:21:52 2023 -0400

**Comment by neuralweights** [comment]
https://tecadmin.net/force-overwrite-local-files-git-pull/#:~:text=The%20simplest%20way%20to%20force,changes%20from%20the%20remote%20repository.

I had the same problem because I have my forked fork of vlad, but I carry these changes from update to update. I had many broken installs until I realized how easy it is. Look at Method 3 in the link, this is what you probably are looking for

**Comment by vladmandic** [comment]
the magic of git. if anyone figures this one out, please let me know - i've tried everything i can think of.
actual git operation is `git pull --autostash --force --rebase` and per git documents, local changes should not interfere when autostash is enabled, but every now and then this still pops up.

**Comment by Woisek** [comment]
I will try this switches, thanks for posting this.

**Comment by Aptronymist** [comment]
> I will try this switches, thanks for posting this.

My advice is to discuss it with ChatGPT a fair bit (though keep in mind it gets things wrong too), I had it write some batch and python scripts and whatnot for me after having it explain some things. For example I made one that would grab a specific PR, by number, and merge it into my local repo. I was using that to apply tons of the lingering fixes and new features way back when Auto1111 vanished and left things untouched for a month just by saying "applypr.py 5423 5232 5584" from inside my repo folder.

**Comment by leppie** [comment]
> git pull --autostash --force --rebase

This actually wiped out my local branch (the branch was called `local` and it was overwritten by `origin/master`). 

I didnt push it anywhere, so all my changes are lost now :(

I would prefer you check out `master` before this command.

**Comment by vladmandic** [comment]
> > git pull --autostash --force --rebase
> 
> This actually wiped out my local branch (the branch was called `local` and it was overwritten by `origin/master`).
> 
> I didnt push it anywhere, so all my changes are lost now :(
> 
> I would prefer you check out `master` before this command.

you should be working off a fork, installer will not change the origin, it will happily use your fork.

**Comment by vladmandic** [comment]
closing as no updates and/or suggestions on how to proceed.

**Comment by Synitare** [comment]
@vladmandic Per this article `git pull` does not respect --autostash for...reasons? You can set `git config rebase.Autostash true`, then `git pull --rebase` will automatically autostash, and the error goes away.

**Comment by Synitare** [comment]
I'll admit that I'm not very familiar with git, but running `git config` in my sdnext directory only modified the config for this specific repo. Specifically it just added:
[rebase]
autoStash = true

To the end of the `PATHTO/sdnext/.git/config` file. No other repos were affected, nor was the global config. It is still technically the user config, but local to the repo unless otherwise specified. There doesn't appear to be any other way to work around the error, at least until git decides to start respecting the `--autostash` switch when used with `pull`. If nothing else this should serve as useful info for anyone that searches a similar issue and stumbles upon this.

**Comment by vladmandic** [comment]
Git config can work on local repo, local user or global. But yeah, this is worth a try.
