### ISSUE TITLE
[Feature] Sortable extra networks

### ISSUE THREAD

**Issue by VStudioAI** [vladmandic/automatic#1337]
Holy Smokes! I just found VD and it's freaking blowing my mind! Not sure what Vlad has done here but i'm getting 2 second renders on my RTX 4080 16GB ram. 

ATTN VLAD! Suggestion - I'm totally loving the interface, VERY slick! Maybe there's a way to do this but here's the idea: I'm downloading all kinds of checkpoints, loras, etc. Looking for a way to organize them by type. For example, realistic, anime, cartoonish, etc.

It would be great if I could put these into a subdirectory of that type, then using a dropdown, select ONLY the assets in that folder for use in my current experiments. Ideally in the Checkpoints dropdown. Is that doable now or can it be added?

Thanks so much Vlad. I sent you an email earlier, please get back to me at your earliest convenience.

**Comment by vladmandic** [comment]
thanks.
saw your email, will reply.

regarding sorting, you can already do that with checkpoints.
for loras, it needs some work on the extension side as extension is responsible for listing/sorting its files, but its doable, just need to take care of few other things first.

**Comment by TheOnlyHolyMoly** [comment]
For a workaround: I have a similar setup, also using aggregate folders (anime, photorealistic, great, trash, second thought) etc... what I do currently is simply changing the root path of the checkpoint and lora directory to the subfolder in my modeltree that is relevant for my current experiments. Anyhow after changing the path it is required the restart since SD main and extensions respond differently to runtime changes of directory...

**Comment by vladmandic** [comment]
as extra networks have been redesigned, closing this in favor of newer feature request #2310
