### ISSUE TITLE
[Issue]: empty prompt produces "woman android" prompt, this is prepended on any prompt

### ISSUE THREAD

**Issue by razvan-nicolae** [vladmandic/automatic#162]
### Issue Description

![image](https://user-images.githubusercontent.com/19169014/232259435-50b550df-adac-4e19-b06c-ac2c7c74eb62.png)
Image speaks for itself - I am stumped lol, I can't find it anywhere in settings.
It seems these 2 words are added to any prompt you use.

Model loaded in 3.6s (load=0.4s create=0.4s apply=0.8s vae=0.9s move=1.0s embeddings=0.1s)
2023-04-16 03:11:01,987 | INFO | I:\SD\automatic\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py | Prompt matrix will create 1 images in a total of 1 batches.
Progress 5.97it/s ---------------------------------------- 100% 0:00:00 0:00:01

I think this is the problem - could explain the lagginess too - why is prompt matrix called when I just run simple prompts?
Either an extension is messing with me, or this from this repo - but my guess is the latter since I definitely don't see this in 1111, and I run exactly the same extensions there, up to date.

Last photo is from 1111, expected behavior
![image](https://user-images.githubusercontent.com/19169014/232259560-369b3f9b-e284-416e-a9a3-56b794398a7c.png)

### Version Platform Description

Windows 11, RTX 4090

commit: [4955a90c](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4955a90c7ba0524e091009e6742e4c805a6dfc60)  
•  checkpoint: [3cb09d984c](https://google.com/search?q=3cb09d984cdd6400fbff3abc1b01c49db952d0c7c7259ee935ba4d2dc3ee74b4)

**Comment by vladmandic** [comment]
`sd-dynamic-prompts` does not ship with this repo - so if you have it installed & enabled, thats a separate story.
uninstall and confim if there are issues. and if its enabled by default after you install it, talk to author and ask him not to enable it automatically.

regarding woman android - never seen that before and it seems related to the same thing most likely.

**Comment by razvan-nicolae** [comment]
Hi, you were right, without this addon this does not happen, however this is specific to this fork, obviously it works correctly in 1111. It's not enabled by default, it just interacts very weird with /automatic. I don't know what to ask the author in this case.

**Comment by arcum42** [comment]
On the "woman android" being added into the prompt, the model keyword extension seems to now be in built in extensions, and it seems likely to be the culprit to me. The times I've tried it in the past, I've tended to quickly disable it due to it triggering on models it shouldn't have and, say, randomly inserting things like "erect penis, flaccid penis, wa-vy style, snthwve style, nvinkpunk, synthwave, sci-fi, caspian sci-fi, star atlas, star citizen, render, postapocalypse, wjqwizard, wjqknight, wjqtitan, wjqjester, wjqautoma, wjqdemon, knollingcase, elden ring style, cyborgdiffusion, cyborgdiffusion style, artificial-journey style, analog style, sks person " in my prompts. 

(That text was actually in the prompt of the first thing I tried to generate after updating..)

I'd try disabling that built in extension and restarting. Not really sure it's one I'd recommend having built in...

**Comment by arcum42** [comment]
Just thought I'd farther confirm that I just looked in the model-keyword.txt file in that extension, and "woman android" is indeed in there.

**Comment by razvan-nicolae** [comment]
i removed it and reenabled dynamic prompt, same thing happens.

**Comment by arcum42** [comment]
Rather than deleting it, go to extensions, uncheck it, and hit apply.

**Comment by razvan-nicolae** [comment]
it's not working, it's always enabled O.o

**Comment by vladmandic** [comment]
its actually very useful, but yes, its annoying since its enabled by default.
until author switches to disabled by default, i'll remove it from list of built-in extensions.
new release will be on github in ~1h.

**Comment by razvan-nicolae** [comment]
thanks. unless you have no idea what you downloaded that extension will never help you reach anything other than random results. And if you don't know what model you just loaded you have bigger problems than that extension can solve.
