### ISSUE TITLE
[Issue]: clip-interrogator-ext won't update

### ISSUE THREAD

**Issue by githubUser01946** [vladmandic/automatic#1755]
### Issue Description

I am clicking update next to it on the Extensions tab and after I restart it still shows that it needs to update.

![image](https://github.com/vladmandic/automatic/assets/117453319/e6e98d10-f9e6-4613-b947-de06f63e77a6)

### Version Platform Description

Google Chrome and your latest update, #0a083c24

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
ask question first if there is no actual issue. this is not an issue since "update" button shows when update may be available. checking if update is for current branch or for some other branch in that repo would be too costly to do ahead of time, so it will do it when you click on it. and then if it tells you no updates available, thats it.

**Comment by githubUser01946** [comment]
That's not what happens.
I click update and it tells me to restart the server but the update button
remains.

So how is it not an issue?

**Comment by vladmandic** [comment]
thats exactly whats happening.
and "restart server" is a safety message that get printed no matter what you do. even if operation results in no changes.

**Comment by githubUser01946** [comment]
So if it has "update" on a button and I click "update" and it says it has updated but the button still says it needs to, how is that not an issue?

**Comment by vladmandic** [comment]
PRs are welcome.
