### ISSUE TITLE
[Feature]: Add stable-fast support

### ISSUE THREAD

**Issue by nRuaif** [vladmandic/automatic#2335]
### Feature description

Recently announced, seemingly offers some pretty sizable speedups on NVIDIA GPUs:
https://github.com/chengzeyi/stable-fast

**Comment by drax-xard** [comment]
Haven't had time to try it yet but it seems very interesting, since it works with diffusers and it *should* play nicely with most features like LoRA, etc.
It does mention that it's a beta and only tested with linux, and I think Triton isn't supported for windows? I may be wrong about it. 
But if we can have almost 2x speedup without needing to resort to TensorRT compile it'd be amazing.

**Comment by vladmandic** [comment]
its on radar.

**Comment by vladmandic** [comment]
closing here as it will be tracked via <https://github.com/users/vladmandic/projects/2?pane=issue&itemId=42265095>
