### ISSUE TITLE
[Feature]: Add Diffusers as a model format for model conversion

### ISSUE THREAD

**Issue by Machinekng** [vladmandic/automatic#2598]
### Feature description

Currently, it is possible to use the Models>Convert tab to convert between ckpt and saftetensors format, but as the UI is shifting towards the diffusers format as the default format, it would be nice to be able to also convert and save models in said format. I notice that diffuser model loading is quicker and more consistent than safetensor model loading, so that may also have performance benefits in the long term.

As I understand it, the model is already converting the saftetensors to diffusers to load it into the diffuers pipeline ([huggingface/diffusers#4095](https://github.com/huggingface/diffusers/issues/4905)) so it should be possible to use the same pipeline tools and then save off the model in this fashion.

### Version Platform Description

app: SD.next
updated: 2023-12-04
hash: 93f35ccf
url: https://github.com/vladmandic/automatic/tree/master

**Comment by vladmandic** [comment]
the request doesn't make sense really, i think there is misunderstanding what is a diffuser format.
safetensors is just weights. you want to load them? where? you need to create model from config and then load them. which scheduler? which text encoder? etc...
diffusers format is a way to create a full model definition - config + weights + everything else that might be needed to create, load and run a model.

and actual weights inside diffusers format can still be safetensors (and as of recently, they actually are by default).

for sd/sdxl you can load safetensors without the rest because a1111/sdnext/etc prepackage config files and schedulers and download text encoder automatically on first use (clip) and whatever is needed.
but for every other model type, it would be a nightmare to prepackage everything.

so converting sd/sdxl is not needed as it all "just works" and converting anything else is impossible unless you have config and that means you already likely have diffusers source.
