### ISSUE TITLE
[Feature]: API Alignment with AUTOMATIC1111 for compatibility

### ISSUE THREAD

**Issue by TheInvisibleMage** [vladmandic/automatic#2633]
### Feature description

I have recently attempted to move from using A1111 to SD.Next. However, in doing so, a few issues have arisen due to slight variations within the APIs between the two:
- The "/refresh-vaes"  endpoint appears to have been renamed to "/refresh-vae" in SD.Next.
- When attempting to get models from "/sd_models", the format in which they are returned seems to have changed, with my attempt being stymied by "model_name" now instead being returned as "name".

As for why this request: Making sure the two APIs remain aligned will ensure that interoperability remains, ensuring moving over to SD.Next is a hassle-free experience.

### Version Platform Description

Branch: Master
Commit: 83785628a32d0bf9f0157b80c7623bd8427711d1

**Comment by vladmandic** [comment]
I'm OK with keeping compatibility whereever feasible, but I need details as I cannot go and test every API request and response on A1111 and then on SDnext myself.

So if this is the goal, provide detailed report - this is a community project and community needs to contribute.

**Comment by Trojaner** [comment]
> And since in Discord you already nailed down one API to exact cause, why not create a PR?

Actually it was me who mentioned the issue on Discord, this issue was created by someone else. I will open a PR.  

This alignment is required for my [text-generation-webui-stable_diffusion](https://github.com/Trojaner/text-generation-webui-stable_diffusion/) extension, which uses SD.Next's API instead of AUTOMATIC1111. However some community members reported compatibility issues with it, such as the VAE list not reloading. Related /refresh-vaes API is used by me [here](https://github.com/Trojaner/text-generation-webui-stable_diffusion/blob/main/sd_client.py#L231).

**Comment by vladmandic** [comment]
Ah, ok.

Well, in either case - PRs are welcome!

**Comment by vladmandic** [comment]
closing as resolved.
