### ISSUE TITLE
[Issue]: SD Upscale and SD Ultimate upscale get progressively worse

### ISSUE THREAD

**Issue by bparrott78** [vladmandic/automatic#264]
### Issue Description

When using either of the SD upscaler or SD Ultimate upscaler, the image becomes progressively worse , as if the CFG is dropping or something.
![image](https://user-images.githubusercontent.com/17459396/233219118-15bf3d02-25da-4ed9-bb46-736dce4de313.png)

### Version Platform Description

Here's my info
![image](https://user-images.githubusercontent.com/17459396/233219220-10eb9a93-ca76-4816-8a60-e0ce6a40d0b2.png)

**Comment by vladmandic** [comment]
haven't used that upscaler in a looong time, but will take a look.
any issues with other upscalers?

**Comment by SqueakyZee** [comment]
@bparrott78 Are you using a different theme, by chance? and your repo is fully updated?

Oddly enough, I was having this exact same issue for the last 3-4 days or so, but after updating to [e6701f5](https://github.com/vladmandic/automatic/commit/e6701f5cb66069e004e0e76ec89a9e212a45f198), and switching the theme back to the default orange/black and restarting, I haven't been able to reproduce the issue even after changing themes back...

Previously, I had tried out different cfg, denoising and other settings but still kept getting that weird smokey affect. I was wondering if maybe it was a clip skip issue or maybe even theme related, because it seems like a random button called "Image CFG Scale" **sometimes** appears and is set to 1.5 by default. 

![image](https://user-images.githubusercontent.com/83526556/233272581-014c1c21-2214-4d0e-90b5-5f2a02bada66.png)

After testing, seems like the Image CFG Scale button appears after running --upgrade, but I still wasn't able to get the weird smokey effect anymore...

All I did when the weird effect stopped, was to: 

1. Set my theme back to the default orange/black theme in settings
2. Applied settings
3. closed the script and webpage
4. ran webui.bat --upgrade
5. let it fully update (which then the Image CFG button probably appears)
6. close the script out again
7. run webui.bat with no extra flags
8. once it starts back up fully, open the web page and the extension was back to working normal for me

The annoying part is that I still don't really know what fixed it, maybe the update, but if OP was already updated, then not that... just, that was my process where it fixed itself. Maybe it was the theme I was using previously (because I did see some errors loading the gradio theme) but well, it's working for me now. I've had this issue for a few days now, but I'm not really going to complain since it so nicely fixed itself.

**Comment by myndxero** [comment]
Couple things to try before I am out. Don't use Latent with denoise under .5, doesn't work well at all. If you used a specific model to generate the image or enhance it prior to upscaling, I've personally found I have more consistent results using that model's inpaint model. When using an inpaint model, you can also make use of the inpainting conditioning extension which can further help.

Making inpaint models is pretty easy by adding difference of 1.5 inpainting and sd1.5 to your 1.5 model, like Deliberate, Clarity, Protogen, etc. 2.x has some better options I am told, but I don't care for it. Depth model in particular if you feel like looking into that. LDSR sampler for best, Swin_IR for second best, ESRGAN if you want fast and preserve details better, R-ESRGAN for more vivid results. Ultrasharp 4x is neat, but third party.

Hope I help in some way. PS - I don't use Ultimate, I don't like, I get better results with regular SD upscale.

**Comment by bparrott78** [comment]
I think I figured out the issue.  I was using this with a LORA in 'model keyword'.  Having this enabled meant that every time the image was iterated on, it added the prompt again.  So, it was doubling the prompt and loading the LORA twice, 3x,4x,5x, etc.  
Disabling the model keyword extension and using kohya-additional-networks has solved the issue.

**Comment by vladmandic** [comment]
ahhhh, good to know!

**Comment by Emersonksc** [comment]
@bparrott78 Wait, What do you mean by "the model keyword", Is it the trigger word for lora? which model key word extension do you refer to?I was totally confused.
