### ISSUE TITLE
[Feature] Ability to configure cache path for interrogator

### ISSUE THREAD

**Issue by sasha0552** [vladmandic/automatic#2668]
### Feature description

Currently, the interrogator cache path is hardcoded at
https://github.com/vladmandic/automatic/blob/bc79cbc2fdf9163854487549384c4f4ab3d5abf2/modules/ui_interrogate.py#L38

I suggest making it configurable in settings, similar to the other paths.

### Version Platform Description

https://github.com/vladmandic/automatic/commit/bc79cbc2fdf9163854487549384c4f4ab3d5abf2 (master branch), [ArchLinux](https://github.com/sasha0552/ToriLinux), Firefox

**Comment by vladmandic** [comment]
any reason? i'm thinking of removing a lot of "configurable" path options since its much easier to configure it once for main models_path.
only critical ones (such as models) should have its own configurable path, the rest should just be relative to configured model_path.

note that previously there were a lot of issues relating to models_path and it was not possible to configure it via ui, so individual paths were used instead. now that it works, why not use it properly.

**Comment by sasha0552** [comment]
Personally, I create an NFS share for each model type, but I don't mind creating only one share (models_path). I just noticed that all paths are configurable except for this one, so I decided to open an issue about it, assuming this isn't intentional.

**Comment by vladmandic** [comment]
i think i'll go in a direction of 
1. core models_dir that is parent for everything
2. allow overrides for checkpoint_dir, diffusers_dir, lora_dir

because those 3 contain user-downloaded content, so flexibility is a good thing. but the rest is mostly one-time thing and size-wise, it never gets as big as either of those 3.
