### ISSUE TITLE
[Feature]: Disable denoising strength input in Control when only using control image-only workflows

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2769]
### Feature description

As the subject says, the denoising strength is applied also to the control image. But for a pure t2i workflow without an independent image, it's hard to see how it could be useful (I set it to 0.01 and images came out fine anyway).

It's probably better to hide it when input is set as "Control image only".

### Version Platform Description

SD.Next dc70246c

**Comment by vladmandic** [comment]
i'm not sure i understand, can you walk me through this?

**Comment by lbeltrame** [comment]
As far as I understand:

- Denoising strength there is applied as in the img2img fashion, isn't it? Meaning over the original control or input image (or control + input) first, then on the subsequent steps
- If you start from a preprocessed image (Control), the actual denoising strength is applied to the *control image* first but the effect on the generated image, when doing a pseudo txt2img workflow (prompt + control image only) amounts to little (I've put it from 0.01 to 0.5 and images came out like they did with t2i, where you can't specify it). 
- If you instead have also an input image, the denoising strength *has* an evident effect (I implemented a pseudo hires fix taking advantage of this fact in my tests).

**Comment by vladmandic** [comment]
denoising strength doesn't even get set for txt2img workflows - so yes, your note is valid.
and yes, ideally, it should only be visible if in img2img or inpaint workflows.
but dynamically changing what's visible is not really viable in this case since decision which pipeline is going to be used is done when you click generate and server analyzes all the settings.
you can see all the details if you set env variable `SD_CONTROL_DEBUG=true` before starting the server.

**Comment by lbeltrame** [comment]
That's fine, thanks, if that's by design.  As long as I know that, I can write notes on how to use it. ;)
