### ISSUE TITLE
[Feature] Control add mask size processing option for inpaint mask only

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#2857]
### Discussed in https://github.com/vladmandic/automatic/discussions/2856

<div type='discussions-op-text'>

<sup>Originally posted by **Silanda** February 13, 2024</sup>
Okay, so my workflow using the img2img module goes like this: I upscale the original image using the SD Upscale script, and then I enhance detail by masking and inpainting certain areas (faces, hands, etc).

I can't inpaint a full 4K image at anything like a reasonable speed, so I set the inpaint resolution to something lower but still larger than the area to be inpainted, and set the inpaint area to masked. The area around the mask is then rendered with more detail and composited back into the full image.

I can't seem to replicate this workflow in the Control module. Rather than only rendering the inpainted area, it seems to render the entire image at the resolution set in the "Before" option, and outputs the final image at that resolution. "Input masked only" doesn't seem to have any effect, and nothing's being composited. In fact, messing with the mask settings with "input masked only" turned on seems to result in an image similar to what's being seen in #2846, rendering the unpainted mask over the resized image. No errors though.

Setting the "After" resolution to the original 4K image's resolution just seems to produce an output that's downscaled the original image, inpainted the whole image at the "before" resolution, and then upscaled it back.

This is on a current dev build and without using any controlnet functionality. 

I was just hoping for some input into whether this is user error on my part, or if the "input masked only" option is malfunctioning, before I open an issue.</div>

**Comment by Silanda** [comment]
It seems to be working to a greater extent now, in that it is now rendering only the area covered by the mask, at the resolution set in the before tab. However, it still seems to have some deal breaking issues.

I don't know if img2img also does this internally, though I'm guessing not, but it seems to distort the aspect ratio of the area being inpainted if the before resolution does not match the ratio of the original image. This is an issue, because things like eyes can end up looking distorted.

Also, the repainted masked area seems to be being composited with a copy of the original image downscaled to the before resolution, rather than with a copy of the original image itself. Setting the after resolution to the original image's size just seems to scale that downscaled composited image to whatever is set. Also, it's not saving the final scaled image anyway; it's ending up in the temp directory unless manually saved, with the saved image being the one rescaled to the before resolution.  

For example, input, intermediate output, and final scaled output. After resize method set to nearest to make it obvious that the final image is not a composite of the inpaint area and the original:

![46193-3197523786-dreamshaperXL_v2TurboDpmppSDE](https://github.com/vladmandic/automatic/assets/4227434/0d06ff6a-72b7-4bb7-9272-cdfc88fe629c)

![46194-2331808389-dreamshaperXL_v2TurboDpmppSDE](https://github.com/vladmandic/automatic/assets/4227434/d047e9cd-0042-433d-98cf-5238b742b030)

![46195--dreamshaperXL_v2TurboDpmppSDE](https://github.com/vladmandic/automatic/assets/4227434/7f9d2c9c-9262-4f02-a422-8c5172206764)

**Comment by Silanda** [comment]
Don't know why I didn't do this before: I tried it with a very low before resolution. 

It confirms what I thought. When processed through img2img, only the inpainted area ends up low res, through Control, the entire image does.

Img2img:

![46196-2797338762-dreamshaperXL_v2TurboDpmppSDE](https://github.com/vladmandic/automatic/assets/4227434/6bc9bb32-c19d-4ea9-a216-a26e6cb79f6b)

Control:

![46199--dreamshaperXL_v2TurboDpmppSDE](https://github.com/vladmandic/automatic/assets/4227434/f813f51a-4309-44a3-9041-540af0f708b0)

**Comment by vladmandic** [comment]
update dev branch once again.
but to move forward, i have to admit i got a bit lost in your latest description - can you document exact workflow step-by-step?

**Comment by Silanda** [comment]
No problem. That test is pretty much my normal workflow but with a lower inpaint resolution. I'll split it into two for img2img and Control, and I'll miss out things like setting the prompt, sampler, steps, etc.

First generate something at 1344x768. 
Copy result to img2img.
Use SD Upscale to do a 3x upscale to 4032x2304

For img2img:

Copy upscaled result to inpaint.
Set resolution to 512x512 with fixed scaling.
Make sure "inpaint area" is set to masked.
Inpaint area.
Generate.
Inpainted area appears to be generated with no change in aspect ratio and final image has the low resolution inpainted area composited into the high resolution input image. 

For Control:

1. Copy upscaled result to Control.
2. Copy to Control inpaint.
3. Check "Inpaint masked only".
4. Set before resolution to 512x512.
5. Set after resolution to 4032x2304.
6. Set appropriate upscalers.
7. Inpaint area.
8. Generate.
9. Intermediate output shows that the area is inpainted but is squeezed as if the 7:4 aspect ratio of the original image is being "corrected" to 1:1.
10. File output into my image folder contains the inpainted area composited in, but seemingly composited into a downscale of the entire image at the "before" resolution and aspect ratio.
11. Upscaled image at the "after" resolution is shown in the UI, but it gets dumped into my Windows temp directory for some reason unless I explicitly save it. It is just an upscale and resize of the low resolution image produced in the last step. It is not a composite of the inpainted area and the original image.

Not setting an upscaler in the "after" tab in Control just results in the squished and shrunk image from step 10 being the final output. 

I've got a nagging feeling that I've missed something, but I hope that helps!

**Comment by vladmandic** [comment]
ok, now i understand. and reproduced.
yes, in img2img if you set resize resolution and inpaint mask only, it will not resize image itself, but it will do that on mask and then apply mask to original image - basically overloading resizing operations.

control module has resize before/after, but they apply to image itself.
what we need is to add one more processing size option for mask. so you could do image resize before and resize after (both if desired), but still process inpainting with mask only at specific resolution.

that is a valid request, but not an issue, it simply doesn't exist in control.
i'll add it to list of missing items.
