### ISSUE TITLE
[Feature]: API + strange thing Process Image tab

### ISSUE THREAD

**Issue by DavidSchobl** [vladmandic/automatic#298]
### Feature description

Hi, I have been using standard automatic-1111 and testing out your UI - I love it. But I have been using a discord bot with a1111 - https://github.com/AndBobsYourUncle/stable-diffusion-discord-bot - it works great, but it requires --api parameter. This parameter is not working with this ui (requires --api-auth which I do not know what it does.).

Can you suggest any workaround AND do you think that bot that worked with automatic1111 could work with yours UI? Would be awesome!

Also, it is not using --xformers?

In Process image tab, I love the UI, but when choosing the model (I use SwinIr 4x), it shows each model 2 or 3 times. Looks strange. It works, but guess it is an issue.
![swinir](https://user-images.githubusercontent.com/109527402/233430621-3f604431-bcd3-40fe-9461-9661dc62a5f3.png)

### Version Platform Description

Chrome, Windows 10, Alienware 15 r3, Geforce 1060Ti

**Comment by Yelorix** [comment]
The API is enabled by default it seems.
I can access it without having to add the --api arg
Are you able to edit the code of your instance of the discord bot? It might work if you just remove the --api argument.

By default, for me at least, this fork launches ith SDP optimization enabled, which as far as I've seen so far, does not work in tandem with xformers but I'm not sure. But for me at least, it provides better optimization (in terms of speed) than xformers does. Using xformers is more performant on the VRAM usage however. But you should be able to set this up so you use xformers instead if you want that

**Comment by vladmandic** [comment]
you can go to UI settings and choose which cross-optimization you want - its always just one. Default is SDP, but you can select xFormers if you want to.

regarding duplicates, yes, its a known gradio issue pending an upstream fix, should be merged soon. i'll close this issue since i'm already tracking that.

regarding `--api`, like @Yelorix said, its always-on here. but some dumb extensions check for command line flag instead of actually checking if its working or not.
i've added compatibility layer for that recently.

**Comment by DavidSchobl** [comment]
Thank you for your great support! ;) I will test it out.
