### ISSUE TITLE
[Feature]: Extra Network - VAE - Display images on cards

### ISSUE THREAD

**Issue by brunogcar** [vladmandic/automatic#2996]
### Feature description

not quite sure if it is a feature request or issue, it goes either and both ways

cos VAE EN doesnt have search civitai icon, 
but it does search all from Models > CivitAi > Start 
and even if you set images to vae manually or from within card details, images arent shown

either way, for exemple VAEs from 
https://civitai.com/models/118561
![vae](https://github.com/vladmandic/automatic/assets/53648/2680c09f-6aa6-45fe-bc58-f478a85fb4e0)
and json and jpeg files downloaded
![explore](https://github.com/vladmandic/automatic/assets/53648/80164a2a-76fd-41d5-a762-2519e6bb5665)
json details are displayed
![blessed](https://github.com/vladmandic/automatic/assets/53648/f3d24ef9-c36c-447f-9554-b5e039e6c282)

it would be usefull to be able to download, set and visualize card images, the same way it works for the other EN, even enabling search CivitAi, from within VAE EN as well

### Version Platform Description

18:16:05-125448 INFO     Version: app=sd.next updated=2024-03-21 hash=82973c49 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master
18:16:05-496563 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
18:16:05-499931 INFO     nVidia CUDA toolkit detected: nvidia-smi present

BTW dev branch, 3efc93b90e6410eb579761e113ad49973e07b448,  not master, but that is the output i got from console

**Comment by vladmandic** [comment]
added in latest dev.

**Comment by vladmandic** [comment]
preview images work fine on my side

**Comment by vladmandic** [comment]
what if you do civitai scan?

regarding junction point, thats fine, but why not just set model-dir in settings?

**Comment by vladmandic** [comment]
OK, that gives me something to look at.

**Comment by vladmandic** [comment]
btw, you should never do this:
> rmdir E:\GitHub\TTI\automatic\models /s /q

feel free to symlink anything inside models (if you're not using models-dir),  
but models itself is maintained by sdnext and tracked as part of the git repo.
doing this 100% will cause issues during any upgrades. also, your reference models section will not work correctly and possibly even taesd and few other things.

**Comment by abdullahcfix** [comment]
I have a similar issue, but for me it's with models as well as VAE.

I used to use Stable-Diffusion-Webui-Civitai-Helper downloading extra networks preview images and it worked fine, but during one of my occasional updates, saw that the feature was baked in as the magnifying glass button at some point in the last few months, so I took it out and did a clean install with only the models in the /model/Stable Diffusion directory, but when I hit the scan button, it just acts like a refresh of the Model Tab in the Extra Networks UI.

It works perfectly fine for Loras and Embeddings with just a couple in each that don't get an image, but not for models.

Personally, I don't have that many VAEs, so those preview images not loading is not an issue for me.

I don't know why, but it's been doing this ever since the feature was added, through all those versions. I'd rather use the built-in feature, if it worked.
