### ISSUE TITLE
[Issue]: VAE folder not found, possible fix for civitai extension compatibility

### ISSUE THREAD

**Issue by angrysky56** [vladmandic/automatic#306]
### Issue Description

I was having some issues with the admittedly beta civitai linker I have and replacing this line back into the automatic sd_vae.py seems to fix it for me, I also added the VAE folder back to the stable diffusion models list. Not a coder just a guess that worked for this so far. It reverts to your sd_vae.py without it with the --upgrade flag btw. Not sure what other issues this could cause.

vae_path = os.path.abspath(os.path.join(paths.models_path, "VAE"))

replaced from-
(https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_vae.py)

https://github.com/civitai/sd_civitai_extension

Also- Edit- this is what is blocking the extra networks button- stable-diffusion-webui-state, it also gave issues with the hi-res fix on automatic1111 btw. If you checked it and restarted the ui it would keep the fix menu from opening.

 solved-webui-state script was blocking my extra networks button from loading lora etc. I have just switched to this branch in the last 24 hours so I am working out what extensions work and deleted a bunch I had installed so not sure what fixed that. I will update on that if anyone is interested. No errors now except-
 Model compile not supported: Windows not yet supported for torch.compile

### Version Platform Description

updated: 2023-04-20
hash: 752b91d3
url: https://github.com/vladmandic/automatic/tree/master

arch: AMD64
cpu: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.9

device: NVIDIA GeForce RTX 3060 (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700

xformers: unavailable
accelerate: 0.18.0
transformers: 4.26.1

Stable Diffusion: [cf1d67a] 2023-03-25
Taming Transformers: [9e9981c] 2022-11-07
CodeFormer: [c5b4593] 2022-09-09
BLIP: [48211a1] 2022-06-07
k_diffusion: [b43db16] 2023-02-06

**Comment by vladmandic** [comment]
<https://github.com/civitai/sd_civitai_extension> should not do a direct access to variables like that, it should read actual settings. but ok, i'll add compatibility for that, correct patch would be `vae_path = vae_path = shared.opts.vae_dir`

> Model compile not supported: Windows not yet supported for torch.compile

that only happens if you enable torch compile in settings - which is 110% experimental and only introduced about 30min ago!

**Comment by angrysky56** [comment]
> https://github.com/civitai/sd_civitai_extension should not do a direct access to variables like that, it should read actual settings. but ok, i'll add compatibility for that, correct patch would be `vae_path = vae_path = shared.opts.vae_dir`
> 
> > Model compile not supported: Windows not yet supported for torch.compile
> 
> that only happens if you enable torch compile in settings - which is 110% experimental and only introduced about 30min ago!

I know- I just wanted to see if it did anything lol.

I tried your code but it broke the ui- 

Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "D:\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "D:\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "D:\automatic\launch.py", line 98, in <module>
    import webui
  File "D:\automatic\webui.py", line 21, in <module>
    from modules import import_hook # pylint: disable=W0611,C0411,C0412
  File "D:\automatic\modules\import_hook.py", line 2, in <module>
    from modules.shared import opts
  File "D:\automatic\modules\shared.py", line 233, in <module>
    default_checkpoint = list_checkpoint_tiles()[0] if len(list_checkpoint_tiles()) > 0 else "model.ckpt"
  File "D:\automatic\modules\shared.py", line 195, in list_checkpoint_tiles
    import modules.sd_models # pylint: disable=W0621
  File "D:\automatic\modules\sd_models.py", line 16, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config
  File "D:\automatic\modules\sd_vae.py", line 8, in <module>
    vae_path = vae_path = shared.opts.vae_dir
AttributeError: partially initialized module 'modules.shared' has no attribute 'opts' (most likely due to a circular import)
Press any key to continue . . .

**Comment by yunghoy** [comment]
Came here since I met the same errors

**Comment by tripletto** [comment]
+1

<pre>Error in sys.excepthook:
Traceback (most recent call last):
  File "c:\stable-diffusion-webui-vlad\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "c:\stable-diffusion-webui-vlad\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "c:\stable-diffusion-webui-vlad\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "c:\stable-diffusion-webui-vlad\launch.py", line 99, in <module>
    import webui
  File "c:\stable-diffusion-webui-vlad\webui.py", line 21, in <module>
    from modules import import_hook # pylint: disable=W0611,C0411,C0412
  File "c:\stable-diffusion-webui-vlad\modules\import_hook.py", line 2, in <module>
    from modules.shared import opts
  File "c:\stable-diffusion-webui-vlad\modules\shared.py", line 233, in <module>
    default_checkpoint = list_checkpoint_tiles()[0] if len(list_checkpoint_tiles()) > 0 else "model.ckpt"
  File "c:\stable-diffusion-webui-vlad\modules\shared.py", line 195, in list_checkpoint_tiles
    import modules.sd_models # pylint: disable=W0621
  File "C:\stable-diffusion-webui-vlad\modules\sd_models.py", line 16, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config
  File "C:\stable-diffusion-webui-vlad\modules\sd_vae.py", line 16, in <module>
    vae_path = shared.opts.vae_dir
AttributeError: partially initialized module 'modules.shared' has no attribute 'opts' (most likely due to a circular import)</pre>

**Comment by vladmandic** [comment]
fixed. i hate when i try to fix one thing, but break another.

**Comment by angrysky56** [comment]
> fixed. i hate when i try to fix one thing, but break another.

Sorry, thanks. I ran the --upgrade and it seems like it is working now after some initial warnings. I think I see the issue, now it is calculating huge sha256 model hashes and lagging my pc just a smidge but it is working. Hopefully it runs through the list once and that is all and then better. 9/it sec on batches of 4 is great for me though!

Calculating sha256 for D:\modeloverflow\illuminatiDiffusionV1_v11.safetensors: cae1bee30e67339dd931925f98c12d2b86fe9f4786795137040e4956f4bfcffe

ha-
Civitai: Updated 144 preview images
