### ISSUE TITLE
[Feature]: Wildcards & Batching

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#3139]
### Feature description

Wildcards currently use the same selection for each image in a batch, though they differ in the results due to the seed changing, this is not the expected outcome.
Each image (from batch size or count) should receive a different result from the wildcards used in the prompt.

Usually this is pinned to the seed, so if you generate the same prompt again (with wildcards) the same wildcard results will be identical if you were to save it as a style and use it again later with the same seed (or hit restore).

Would need to check dynamic prompts for how they handle that, but it's rational and logical behavior to maintain reproducible results.

**Comment by vladmandic** [comment]
done, but this was a bit more complicated since our templates allow much more than dynamic prompts
e.g. varying prompt in batch is nice, but varying params is not - imagine if trying to set different resolution for images inside same batch?

anyhow, prompts are now randomized within batch, params are randomized once per-batch and prompts also use seed as random seed for choice from wildcards so they are reproducible.

**Comment by Aptronymist** [comment]
> done, but this was a bit more complicated since our templates allow much more than dynamic prompts e.g. varying prompt in batch is nice, but varying params is not - imagine if trying to set different resolution for images inside same batch?
> 
> anyhow, prompts are now randomized within batch, params are randomized once per-batch and prompts also use seed as random seed for choice from wildcards so they are reproducible.

Fantastic, and yeah, I know you can't do a lot of that, and it's not necessary by any means, as long as these prompts are good, I think we're fine for now.
