### ISSUE TITLE
[Issue]: All about NaN errors or Black images generated

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#374]
### Issue Description

I'm creating a new issue to unify all issues related to:
- NaN errors during generation
- Generate creates all black images

First, note that command line flags such as `--no-half` or `--no-half-vae` are **not longer present** or applicable.  
If you were previously using them, set according settings in **UI -> Settings -> CUDA Params**

Second, there have been several fixes posted very recently, so update your repo to:
> Version: 61e9a197 Sat Apr 22 08:35:13 2023 -0400

- If you're getting `NaN` errors, you can try enabling setting:
  - "Do not check if produced images/latent spaces have NaN values"
- If you're getting all black images, try different combinations of:
  - Precision type: Full
  - Device precision type: FP32
  - Use full precision for model
  - Use full precision for VAE

There is no single setting that fits everyone.  
Also, setting higher precision may alleviate errors due to higher math precision, but it also slows down generation, so they are not enabled by default.

Note that after changing any of the CUDA settings, you must restart **WebUI** from command prompt. Restarting server from UI is not sufficient.

If you're still having issues after the steps taken above, please post update to this issue with:
- Version information
- CUDA settings (do not post screenshots, write them down)
- You platform details (OS, GPU, etc.)
- Exact workflow used - how to reproduce
- Model and VAE used

There have been too many "I also have issue" posts without providing any information.

**Comment by keny25** [comment]
During a flesh install applying changes in the UI changed settings I had not changed.

I was able to solve my problem of black images by changing ldsr_steps, ldsr_cached, SWIN_tile and SWIN_tile_overlap to lower values.

Version information: 04/21/2023 ver
CUDA settings:

Precision Autocast
Device type FP16
No half vae
No NaN check
Allow TF32
Allow TF16
Model compile none

You platform details: Win10, 1060 3gb, 16gb ram
Exact workflow used: flesh install => change VAE => apply changes => black images => return to old VAE => still black images
Model and VAE: AOM3, anything 3.0 vae

**Comment by The-Noble** [comment]
I've noticed that I only seem to get this error when I try to high res fix past 2x size.
On bigger images, I have to do 1.75x size to get this error to not appear. I find it odd that it's tied to size.

**Comment by dhkaneda** [comment]
Like @The-Noble, I'm using hi res fix past 2x. As the errors suggests and @vladmandic, I was able to fix my issue in in **UI -> Settings -> CUDA Params** with these enabled:
- "Do not check if produced images/latent spaces have NaN values"
- "Use full precision for VAE"

I reproduced my black image errors in Automatic1111's webui to receive this msg:

> NansException: A tensor with all NaNs was produced in VAE. This could be because there's not enough precision to represent the picture. Try adding --no-half-vae commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.
Time taken: 29.82s
Torch active/reserved: 4778/6226 MiB, Sys VRAM: 8530/12282 MiB (69.45%)

in A1111, it was fixed using commandline args `--no-half-vae` and `--disable-nan-check commandline`, back in vladmandic/automatic with CUDA settings.

I did try a whole host of combination of those CUDA settings before trying to reproduce my workflow back in A1111 and actually read errors. Thought I'd post here in case anyone else runs into something similar and wants to try out these two settings before blindly trying the others.

Model used: Dark Sushi Mix
VAE: orangemix,vae.pt
Win 11, RTX 4070 Ti 12gb VRAM, 32gb RAM
Version: [4cb46d5](https://github.com/vladmandic/automatic/commit/4cb46d5400b04491ae9e70d992ca0019d48942a9) April 22, 2023

**Comment by vladmandic** [comment]
FYI, latest version has new (experimental) feature: UI -> Settings -> CUDA Params -> "Attempt to roll back VAE when produced NaN values, requires NaN check"

**Comment by AbramovS1** [comment]
> ### Issue Description
> I'm creating a new issue to unify all issues related to:
> 
> * NaN errors during generation
> * Generate creates all black images
> 
> First, note that command line flags such as or are **not longer present** or applicable. If you were previously using them, set according settings in **UI -> Settings -> CUDA Params**`--no-half``--no-half-vae`
> 
> Second, there have been several fixes posted very recently, so update your repo to:
> 
> > Version: [61e9a19](https://github.com/vladmandic/automatic/commit/61e9a1970ce6461a93a08b700466f8b8fcd5421b) Sat Apr 22 08:35:13 2023 -0400
> 
> * If you're getting  errors, you can try enabling setting:
>   `NaN`
>   * "Do not check if produced images/latent spaces have NaN values"
> * If you're getting all black images, try different combinations of:
>   
>   * Precision type: Full
>   * Device precision type: FP32
>   * Use full precision for model
>   * Use full precision for VAE
> 
> There is no single setting that fits everyone. Also, setting higher precision may alleviate errors due to higher math precision, but it also slows down generation, so they are not enabled by default.
> 
> Note that after changing any of the CUDA settings, you must restart **WebUI** from command prompt. Restarting server from UI is not sufficient.
> 
> If you're still having issues after the steps taken above, please post update to this issue with:
> 
> * Version information
> * CUDA settings (do not post screenshots, write them down)
> * You platform details (OS, GPU, etc.)
> * Exact workflow used - how to reproduce
> * Model and VAE used
> 
> There have been too many "I also have issue" posts without providing any information.
> 
> ### Version Platform Description
> _No response_

If I make these settings, then I can no longer run the program, and it shows that there is not enough memory

**Comment by vladmandic** [comment]
> If I make these settings, then I can no longer run the program, and it shows that there is not enough memory

It clearly says: `If you're getting all black images, try different combinations of:`

you most likely don't need all of it and there is no one-size-fits-all as it heavily depends on GPU and model used.

**Comment by vladmandic** [comment]
"but I had a1111 working fine" doesn't mean much anymore - pretty much all of core libraries here are updated and yes, they have different memory requirements and different settings. You're free to go back.

**Comment by AbramovS1** [comment]
> "but I had a1111 working fine" doesn't mean much anymore - pretty much all of core libraries here are updated and yes, they have different memory requirements and different settings. You're free to go back.

Even taking into account the fact that I put torch 2 with my own hands and calmly generated images with the low vram parameter, it's sad that not everyone wants to do optimization

**Comment by ubemotho** [comment]
![image](https://user-images.githubusercontent.com/1352206/235646607-0bf7e8da-b093-4312-8bd9-9d211ed9955f.png)
in old commit 149329cb i only used --no-half-vae with medvram and xformers 
1660ti when i used this settings its working without black image. thanks to @vladmandic works it's little bit faster too
one question @vladmandic is Enable upcast sampling need enabled Use full precision for model (--no-half)  if so when user enable upcast sampling it should automaticly enable Use full precision for model too for user experience.
thanks again.

**Comment by vladmandic** [comment]
those three options may do a very similar thing, but in different areas:
- `no-half` means when model is loaded, it wont be converted to fp16, it will stay as-is.
- `no-half-vae` means when VAE is loaded, it wont be converted to fp16, it will stay as-is.
- `upcast-sampling` does the same, but only to unet/upsampler part of the model, not entire model. so if you already have `no-half`, this is irrelevant.

**Comment by ubemotho** [comment]
![image](https://user-images.githubusercontent.com/1352206/235660001-0e81dee5-c659-4cce-871c-9c36ae3a2f4e.png)
thanks for the explanation. when i disabled no-half it generate black image so upcast-sampling doesnt fix it on 1660ti

it's working really weird in my 1660ti when sd first came out we have to use no-half or it generate green image
then xformers came i don't know why but it works without no-half only flags i use was --medvram --xformers max performance was like 0.60-0.7 it/s
then i installed your fork in 14 april it was 2.5x faster with --no-half --medvram --xformers/--sdp 1.6-1.7 it/s
then now with no-half medvram and xformers i got up to 1.97 it/s thanks to you @vladmandic
 
it's really weird because this card has dedicated  fp16 cores [according to this article](https://www.anandtech.com/show/13973/nvidia-gtx-1660-ti-review-feat-evga-xc-gaming/2) and says **_"To users and developers this shouldn’t make a difference – CUDA and other APIs abstract this and FP16 operations are simply executed wherever the GPU architecture intends for them to go – so this is all very transparent."_**
i think no one give good look at it because it is only 16xx series problem and those old cards now but problem is intriguing i hope someone find where is the problem i want to read analysis of it.
 is it because off cuda api? or sd implementation of cuda api?

**Comment by vladmandic** [comment]
in theory yes, in practise - fp16 was only introduced on 1000 series cards, so its 1st generation and their implementation was a bit buggy. its doesn't really work as fp16, more like fp14, so its lacks precision - thats why you end up with NaNs or black images. newer cards implement fp16 as real 16-bits so this "borderline math precision issue" is much lower.

also, each nvidia card reports its capabilities to cuda/cudnn, so cuda can decide which functions to execute. and older cards report lower capabilities, so many new cuda fixes/improvements are not even triggered. you can see capabilities reported by your card as string in system info
> device: NVIDIA GeForce RTX 3060 (1) (sm_90) (8, 6)

where `sm_90` is internal gpu architecture (e.g., they map to codenames such as `pascal`, `ampere`, `turing`, `volta`, `ada`, etc.) and `8.6` are its reported capabilites

**Comment by moonshinegloss** [comment]
```
Python 3.10.11 on Windows
Version: e324e54c Wed May 3 10:36:08 2023 -0400
Torch 2.0.0+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
```

CUDA settings

```
vram usage polls: 2
precision type: full
device precision type: fp32
use full precision for model: yes
use full precision for vae: yes
do not check if produced images/latent spaces have NaN values: yes
allow TF32 math ops: yes
allow tf16 reduced precision math ops: yes
model compile mode: none
model compile verbose mode: yes
model compile suppress errors: yes
```

You platform details: Windows 11, Nvidia 4090 (driver version: 531.79)
Exact workflow used: typed "test" pressed generate
Model and VAE used: https://civitai.com/models/46294/diffusion-brush-everything-sfw-nsfw-all-purpose-checkpoint-nuclear-diffusion-anime-hybrid (no vae and auto, both create black screens)

**Comment by Rudy34160** [comment]
__15:01:42-333426 INFO     Python 3.10.11 on Windows
15:01:42-750381 INFO     Version: 6f976c35 Tue May 2 21:30:31 2023 -0400
15:01:43-154927 INFO     Latest published version: b401d9ed3d49153a21ee4af974e76691b7ae2054 2023-05-03T12:40:50Z
15:01:43-156948 INFO     Setting environment tuning
15:01:43-160939 INFO     nVidia CUDA toolkit detected
15:01:45-511878 INFO     Torch 2.0.0+cu118
15:01:45-538971 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:01:45-542365 INFO     Torch detected GPU: NVIDIA GeForce GTX 1650 VRAM 4096 Arch (7, 5) Cores 14
15:01:45-543362 INFO     Installing package: xformers==0.0.17
15:01:51-721747 INFO     Verifying requirements
15:01:51-793271 INFO     No changes detected: Quick launch active
15:01:51-801321 INFO     Running extension preloading
15:01:51-803301 INFO     Server arguments: []
15:02:01-409865 INFO     Libraries loaded_

_Cross-attention optimization method : Split attention__ (I leave the optimizer on Split because it is only with this one that I manage to use Controlnet)

_Prompt : a sad man (Euler A, steps 20, CFG 7)_

I think I tried all the possible combinations in the CUDA settings tab, but I always get a black generated image. And on some settings, I get the error below at startup.

__Loading weights: C:\Ai_Folder\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV13_v13VAEIncluded.safete…
15:03:30-103623 INFO     Creating model from config: C:\Ai_Folder\Vladmandic-webui\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: C:\Ai_Folder\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt ------ 334.7… 0:00:00
                                                                                                         MB
15:03:35-529431 ERROR    loading stable diffusion model: OutOfMemoryError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Ai_Folder\Vladmandic-webui\automatic\webui.py:152 in load_model_                                                  │
│                                                                                                                     │
│   _151 │   try:                                                                                                      │
│ > 152 │   │   modules.sd_models.load_model()                                                                        │
│   153 │   │   modules.sd_models.skip_next_load = True                                                               │
│                                                                                                                     │
│ C:\Ai_Folder\Vladmandic-webui\automatic\modules\sd_models.py:395 in load_model                                      │
│                                                                                                                     │
│   394 │   else:                                                                                                     │
│ > 395 │   │   sd_model.to(shared.device)                                                                            │
│   396 │   timer.record("move")                                                                                      │
│                                                                                                                     │
│                                               ... 9 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Ai_Folder\Vladmandic-webui\automatic\venv\lib\site-packages\torch\nn\modules\module.py:820 in _apply_             │
│                                                                                                                     │
│    819 │   │   │   with torch.no_grad():                                                                            │
│ >  820 │   │   │   │   param_applied = fn(param)                                                                    │
│    821 │   │   │   should_use_set_data = compute_should_use_set_data(param, param_applied)                          │
│                                                                                                                     │
│ C:\Ai_Folder\Vladmandic-webui\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1143 in convert           │
│                                                                                                                     │
│   1142 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                                   │
│ > 1143 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No                     │
│   1144                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.39 GiB already
allocated; 0 bytes free; 3.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
15:03:35-718088 ERROR    Stable diffusion model failed to load
Appuyez sur une touche pour continuer..._

If someone managed to make this fork work with this hardware or if someone has an idea to propose, I'm interested, because I don't know what to try anymore... 🤨

**Comment by EfourC** [comment]
@Rudy34160 I recommend starting a different discussion thread for your issue, it's not related to this thread about NaN errors/black images at all.

**Comment by vladmandic** [comment]
@moonshinegloss

you have RTX4090, why do you need to use FP32? thats primarily for GPUs that have broken or unsupported FP16?
Same for autocast.
And no-half and no-half-vae is pretty much for badly trained models that misbehave on FP16. It was common in early days, but now there are sooo many quality models. btw, your settings will also kill 50% of your performance, if not more.

and your compile settings? why tinker with those? it says experimental and its really only for people that are testing torch nightly builds, not 2.0 general release.

i just tried your *diffusionbrush-everything* model and it seems to work fine with default settings.

**Comment by moonshinegloss** [comment]
@vladmandic I only did those because your original post suggested them to try to resolve the issue, I fully reinstalled and kept default, the model still black screens sadly, I can see the image generate for some amount of steps and then right before it's about to finish it blackscreens.

not sure what "compile" settings are? that was just out of the box what it was set to for me, I only changed the few things you mentioned in the original post, but listed everything that was activated.

**Comment by vladmandic** [comment]
Can you uncheck `Do not check if produced images/latent spaces have NaN values` and restart server. If you get error reports about NaN values, then its the same problem as discussed here. If you get no errors, we're talking about something different.

**Comment by moonshinegloss** [comment]
alright interesting, if I toggle the VAEs around after a fresh start, it works, but if I leave it on auto or none, it'll blackscreen onwards

**Comment by vladmandic** [comment]
@moonshinegloss that is very curios. i'll play around with that. i wish i could reproduce, then it would be much easier to fix.

**Comment by Rudy34160** [comment]
> @Rudy34160 I recommend starting a different discussion thread for your issue, it's not related to this thread about NaN errors/black images at all.

@EfourC 

🤨🤨

[[Issue]: All about NaN errors or Black images generated]

I do have a problem generating black images, I don't see how my post is off topic...

**Comment by vladmandic** [comment]
@Rudy34160 yes, you did state that `I think I tried all the possible combinations in the CUDA settings tab, but I always get a black generated image. And on some settings, I get the error below at startup.`, its just the long traceback at the end can be misleading. but it is on-topic.

**Comment by EfourC** [comment]
Whoops, my apologies! @Rudy34160 I did completely miss that

**Comment by Rudy34160** [comment]
> yes, you did state that `I think I tried all the possible combinations in the CUDA settings tab, but I always get a black generated image. And on some settings, I get the error below at startup.`, its just the long traceback at the end can be misleading. but it is on-topic.

Apologies if I misspoke or misunderstood, English is not my native language. I just wanted to say that with some CUDA settings I was getting black images, and sometimes when changing those same settings I was getting the error described in my previous post.
The fork seems to work on my 1650 card (by activating t2i_color_grid, I manage to have the result in my window) but with a black image.

**Comment by Rudy34160** [comment]
> Whoops, my apologies! @Rudy34160 I did completely miss that

No prob

**Comment by EfourC** [comment]
Here is an example I can always repeat (on my hardware) that has some interesting differences in behavior, depending on settings.

I think the noteworthy aspects are:
1. Enabling `Hires fix` actually affects the first-pass image, making it's output file completely black, whereas it is ok without Hires fix.
2. Using a `Latent` upscaler allows the **second-pass** image to generate properly, but using **non**-Latent upscalers don't.  And, either way the first pass image was ok in `Live Preview` but **not** in output file).

The above seems to imply that the different relevant code sections aren't pulling the image data out of the GPU the same way.

3. Side note: The 'Upscale by' multiplier value doesn't seem to affect the results.

Settings where I see the problem:
<details> <summary> Click to expand... </summary>

![chrome_XXOS6qXdnW](https://user-images.githubusercontent.com/121468033/236090731-21493947-be8d-41dd-bff5-c55e7a8440da.png)

![chrome_UZZpmlrVnR](https://user-images.githubusercontent.com/121468033/236090750-6698521f-5547-4ecd-9d42-1c17ad0d2e4b.png)

</details>

If I instead use full precisions/FP32 for all `CUDA Settings`, the black image problem doesn't happen (but it's super slow, of course).
<details> <summary> Full precision settings screenshot... </summary>

![chrome_rf9koHCYVw](https://user-images.githubusercontent.com/121468033/236090544-4150a9bc-4d24-42b9-8676-64fe290c3235.png)
</details>


### Example image info:
```
Prompt:  masterpiece, sweeping mountain view
Negative prompt:  lowres
Steps: 25,  CFG scale: 7, Seed: 3869183259, Size: 768x512,
Model hash: e06702b274, Model: Anything-v5, Denoising strength: 0.7,
Clip skip: 2, Hires upscale: 1.5, 

Sampler: <varies, see details>,
Hires upscaler: <varies, see details>
```
This particular example was done with the Anything-v5 model (no extra VAE), but of course different models don't always manifest the problem for the same seed+settings.

### Results:
**Case 1:** No Hires
- `Hires fix` disabled

If the Hires fix option is not used, the image generates fine, both in live preview and the output file.

**Case 2:** Latent upscaler
- `Hires fix` enabled
-  Any non-ancestral Sampler
-  Any `Latent` Upscaler variant

First-pass image is fine in Live Preview, but **NOT** the output file (solid black).
Second-pass image is fine in Live Preview, and is fine in the output file.

**Case 3:** Non-Latent upscaler
- `Hires fix` enabled
- Any non-ancestral Sampler
- Any non-Latent Upscaler (e.g. None, SwinIR_4x, Nearest, etc.)

First-pass image is fine in Live Preview, but **NOT** the output file (solid black).
Second-pass (after upscale) image has a black live preview and nearly(\*) black output file.

 (\*Note) There is some noise and artifacts in the second-pass image which can be seen if gamma correction is applied. Also, LDSR generates a totally different second-pass image than the first pass preview, so my guess is it's based off of same low-level noise/artifacts but manages to make more of an image out of it instead of mostly black.

**Case 4:** Ancestral sampler
- `Hires fix` enabled
- Any ancestral Sampler
- Any Upscaler

This particular seed didn't generate black images for any ancestral samplers (all ok), but I don't know if that's by pure chance for this seed or an important difference.


### Image outputs for each case:
<details> <summary> [Click to expand...] </summary>
Case 1 image (no Hires fix):

![00119-3869183259-25](https://user-images.githubusercontent.com/121468033/236089403-4a6da95b-f6f8-4995-9abb-d49fd934cec2.png)

Case 2 images (Latent upscale):

![00120-3869183259- steps -before-highres-fix](https://user-images.githubusercontent.com/121468033/236091079-ca632ea5-1937-4d11-a56f-66b50bfa05e4.png)

![00121-3869183259-25](https://user-images.githubusercontent.com/121468033/236091097-cd490759-d445-411f-9734-f518886cee86.png)

Case 3 images (see artifacts in the second-pass image):

![00122-3869183259- steps -before-highres-fix](https://user-images.githubusercontent.com/121468033/236091401-8bf75362-ccdc-4a99-9d54-ce3118a20d2c.png)

![00123-3869183259-25](https://user-images.githubusercontent.com/121468033/236091409-ca3663ed-78a3-428d-ac11-0db0358a2eb0.png)

Case 4 images (ancestral):

![00124-3869183259- steps -before-highres-fix](https://user-images.githubusercontent.com/121468033/236091516-fda14ab0-2c68-4657-a451-fbc996a2c2b2.png)

![00125-3869183259-25](https://user-images.githubusercontent.com/121468033/236091526-4cdc09f5-dd09-458b-816c-01d40312091e.png)


</details>


### WebUI version and startup log:
<details> <summary> [Click to expand...] </summary>
Version: e0543e44 Wed May 3 19:15:18 2023 -0400

![WindowsTerminal_mOlRewqjtq](https://user-images.githubusercontent.com/121468033/236090918-5a6da799-f8fa-4837-ab17-dffa2639a94f.png)

</details>

**Comment by vladmandic** [comment]
This is very useful, but it's going to take me some time to digest...

**Comment by EfourC** [comment]
No rush! It took a while to write haha

**Comment by vladmandic** [comment]
@EfourC i've added auto-test code for fp16 functionality so it can determine if it can use it safely - can you upgrade and test?

**Comment by EfourC** [comment]
Just tied, but see same result.  (To be clear, not all seeds generate black images with this model, just some.)
Version: 8c981159 Thu May 11 14:20:27 2023 -0400
<details> <summary>[Click to expand...]  Startup log and System Info tab</summary>

![WindowsTerminal_sB7eBSHQ7G](https://github.com/vladmandic/automatic/assets/121468033/9e744b9b-927d-4fd4-84cc-3a9ed0942675)

![chrome_XDLiaTafi1](https://github.com/vladmandic/automatic/assets/121468033/386c7a57-4511-4a72-a522-43db1a36c58a)

</details>

**Comment by EfourC** [comment]
I still can't figure out why the first image is just fine if `Hires fix` is disabled, but is black when enabled.

When I outputted (to file) and compared the tensors being passed into `decode_first_stage()` from the different codes paths of the 2 cases (Hires enabled and disabled), the contents perfectly matched.
I'll probably try that again to double check, as well as check what `disable` is getting set to in `decode_first_stage()` for each case:
```python
def decode_first_stage(model, x):
    with devices.autocast(disable = x.dtype==devices.dtype_vae):
        x = model.decode_first_stage(x)
    return x
```

**A side note:**
I noticed that the test_for_nans() functionality isn't run for the intermediate images with Hires fix on.

I attempted to get the 'recovery' functionality after test_for_nans() (in the except block) to run by kludging over the code into `single_sample_to_image()` but I wasn't successful so far (then I got sick with flu, so stopped).

**Comment by vladmandic** [comment]
@EfourC that is pretty weird. assuming its true, that means that hires changes dtype of the tensor so autocast in decode function corrupts the results.
neither should happen (autocast should work - that's why it exists), but hires should not change dtype to start with.
can you do a print of dtype before and after hires and also print desired dtype (devices.dtype.vae)?

**Comment by EfourC** [comment]
Ok I modified `decode_first_stage` with the latest commit to print:

```python
from inspect import currentframe, getframeinfo  # For testing
def decode_first_stage(model, x):
    frameinfo = getframeinfo(currentframe())
    print("In function: ", frameinfo.function, "Line:", str(frameinfo.lineno) + ",", frameinfo.filename)

    with devices.autocast(disable = x.dtype==devices.dtype_vae):
        print("  Pre-decode: ", "x.dtype=" + str(x.dtype) + ", devices.dtype_vae=" + str(devices.dtype_vae))
        x = model.decode_first_stage(x)

    print("  Post-decode: ", "x.dtype=" + str(x.dtype) + ", devices.dtype_vae=" + str(devices.dtype_vae))
    print("")
    return x
```

It does show a change in dtype for the intermediate image for some reason:

![aklsM8xZMX](https://github.com/vladmandic/automatic/assets/121468033/bc8dde6b-64cb-4aaf-8808-851a38eb4141)



Version: 1921504e Fri May 12 15:58:00 2023 -0400

<details> <summary>Startup log + System Info tab</summary>

![gs97kCtl38](https://github.com/vladmandic/automatic/assets/121468033/ccb96518-6097-4382-a50a-60467f5d7a63)

![chrome_5GPaKbVApY](https://github.com/vladmandic/automatic/assets/121468033/8881999d-c1b4-4f3e-b1ee-1b90d51f02c7)

</details>

By the way, I'm also seeing painfully slow performance for the first gens of any given resolution on the latest commits. I'll try to narrow down the specifics.

**Comment by vladmandic** [comment]
> painfully slow performance

which platform & gpu? what are your cuda settings?

**Comment by EfourC** [comment]
CPU:  Intel 3770k
GPU:  RTX 2070 Super
Windows 10

![chrome_9a4IbE8Zmo](https://github.com/vladmandic/automatic/assets/121468033/54e67be4-322f-4270-9f14-4529a3f1ee9e)

**Comment by vladmandic** [comment]
i think i have an idea - older rtx cards have semi-broken fp16 mode which somehow wakes up when cudnn.benchmark is enabled, but that means that cuda spends extra time doing additional benchmarking first time it sees a new operation (it does that so it can determine which execution method is optimal). i've added that to allow older cards to work with fp16, but it causes those delays. but i can limit the benchmark depth to 1, so its still enabled but does its just much faster.

i'm also adding two casts in hires that call decode_first_stage, lets see if that helps with mixed dypes.
i'd appreciate a quick test before i get tons of people reporting new issues because of that :)

**Comment by EfourC** [comment]
Ok just checked with:
Version: a2485cf7 Fri May 12 21:12:24 2023 -0400

Performance back to normal, but the black image issue remains.

**Comment by vladmandic** [comment]
if you can redo your test with tensor dtype checks, i'd appreciate it - i believe its really specific to RTX1xxx and RTX2xxx GPUs only and i don't have that to test.

**Comment by EfourC** [comment]
Not a problem

Version: a2485cf7 Fri May 12 21:12:24 2023 -0400
![WindowsTerminal_WrKXxoq7jR](https://github.com/vladmandic/automatic/assets/121468033/354bd6f0-d12a-4099-878e-757223bfec64)

<details> <summary>Startup log...</summary>

![nkS2vnOfmW](https://github.com/vladmandic/automatic/assets/121468033/dad283ba-b279-479c-8a6f-30f6301891ee)

</details>

**Comment by vladmandic** [comment]
can you do settings -> image options -> disable all that say "save a copy"

**Comment by EfourC** [comment]
Disabled the 3 'save a copy' options I saw, and results were the same.

**Comment by vladmandic** [comment]
since you're ok modifying code, can you do this in `modules/sd_samplers_common.py`
```python
def sample_to_image(samples, index=0, approximation=None):
    return single_sample_to_image(samples[index].to(dtype=devices.dtype_vae), approximation)
```

**Comment by EfourC** [comment]
> since you're ok modifying code, can you do this in `modules/sd_samplers_common.py`
> 
> ```python
> def sample_to_image(samples, index=0, approximation=None):
>     return single_sample_to_image(samples[index].to(dtype=devices.dtype_vae), approximation)
> ```

Got same results for this too

**Comment by vladmandic** [comment]
@EfourC this kinda fell into my backlog, just checking if there is anything new?

**Comment by EfourC** [comment]
No worries - nothing new from me, I've been busy with other things also. Although I definitely appreciate the time and attention you've given this issue so far!

**Comment by Gerkinfeltser** [comment]
Hello! I seem to be having the same issues as folks above. (Even down to the diffusionbrush among others, resulting in black.)

I'm on windows 10 and have a NVIDIA GeForce GTX 1070. I've tried various combinations posted in this thread but still no luck getting out of the NaNs. Is there any other information that would be useful for debugging @vladmandic?

**Comment by moonshinegloss** [comment]
Diffusionbrush works for me with VAE on, without any or on auto, it'll black screen for me too, the toggling VAE on/off from before didn't seem to work anymore.

**Comment by az1fr3** [comment]
> CPU: Intel 3770k GPU: RTX 2070 Super Windows 10
> 
> ![chrome_9a4IbE8Zmo](https://user-images.githubusercontent.com/121468033/238102997-54e67be4-322f-4270-9f14-4529a3f1ee9e.png)
> 
> **EDIT:** I have to be afk for a bit, but I'll add some timing printouts when I return to demonstrate. There seems to be extra slowness during each part of the first image generation at a resolution: 'initializing', sampling, and also during decoding.

This configuration works for me i`m in windows 11 CPU: intel i5-9300H 2.40Gh  GPU: GTX1650 4gb Ram:12gb

**Comment by chdelacr** [comment]
This is also happening on my end, but one thing I've noticed is that my VRAM gets loaded with 2+ GB just by launching _automatic_. I can't find any setting to prevent this, and this is what I get NaN errors and nothing from this thread has made the trick.

**Comment by vladmandic** [comment]
closing the issue as its not being actively worked on, but more used as a reference. if anyone has an issue after reading this thread, create a new issue as its not really possible to keep track of updates.
