### ISSUE TITLE
[Feature]: Multi-GPU Image Generation / Inference

### ISSUE THREAD

**Issue by rbychn** [vladmandic/automatic#405]
### Feature description

It'd be cool if this could run a single inference on multiple GPUs at the same time to speed up the process for people who have them.

Running multiple generations takes a lot of time and getting it to run on all of them would make it a lot faster when running on higher batch counts and sizes.

**Comment by vladmandic** [comment]
sure, but you need to join gpus on a layer waaay below the app.
search on google how to do it. also, do you want parallel, shared or distributed usage.

in either case, its not something that should be done on app level.

**Comment by baaoh** [comment]
My use of multiple gpus is like this:
I use "set CUDA_VISIBLE_DEVICES=0" for my webui-user.bat, and it launches the UI using only first gpu, I then launch two more UIs with different args (set CUDA_VISIBLE_DEVICES=1 and set CUDA_VISIBLE_DEVICES=2) and different ports, this is the only way I managed to parallelize the GPUs, dont know if there can be a more elegant way.

**Comment by rbychn** [comment]
@baaoh so like is there no way for me to run the same UI on different GPUs? If I were to do a large batch I'd prefer it run on all 3 of them so that it's faster and take less time compared to running it on just one GPU. I'm not sure I can achieve that by running 3 UIs?

**Comment by baaoh** [comment]
@rbychn correct, i set each .bat to see only one of my GPUs, and I can then launch 3 seperate UIs, each only work with the specific GPU (0,1,2). It is sometimes laggy, since there is still only 1 CPU. Pain is they are completely separate, so can't transfer prompts or images between each other, but I can work on 3 generations at the same time.

**Comment by ilikenwf** [comment]
I don't currently have multiple GPUs, but if we got this working, could justify getting an older tesla for vram or something later - other projects are discussing this and some docker has added a wrapper script to somehow handle this...

https://github.com/NickLucche/stable-diffusion-nvidia-docker/blob/master/parallel.py

Relevant discussion:
https://github.com/NickLucche/stable-diffusion-nvidia-docker/issues/8

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/311

**Comment by vladmandic** [comment]
Yeah, but that only splits the batch to multiple cuda devices, it's doesn't use multiple device for a single job.

**Comment by Anonym0us33** [comment]
Multiple devices is still useful. I use a script to use a tesla but it's become buggy recently maybe due to windows maybe due to git pull maybe due to python version maybe due to drivers, i'm not sure. But for runs over 10 images, even the old teslas can generate at 25-50% of the speed of a mid spec RTX in AUTOMATIC111.
like this
```
set CUDA_VISIBLE_DEVICES=0
start python launch.py --port 7861
set CUDA_VISIBLE_DEVICES=1
start python launch.py --no-half-vae --port 7862
set CUDA_VISIBLE_DEVICES=2 
start python launch.py  --no-half-vae --port 7863
```
