### ISSUE TITLE
[Issue]: Differences between Transformers versions

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#422]
### Discussed in https://github.com/vladmandic/automatic/discussions/407

<div type='discussions-op-text'>

<sup>Originally posted by **BlackWyvern** April 23, 2023</sup>
So I'm linking this in here, [#7351](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7351) as I still am unable to generate images using that version of transformers in the requirement files.

If I downgrade the requirement to 4.19.2, it works fine. But, this issue is persisting across multiple different branches and generators. So, it's not a localized issue to simply A1x4

I'm out of ideas, and the few other places I've tried asking around in were met with silence.

So, as a more generalized discussion area, are there perhaps any other insights out there?</div>

**Comment by myndxero** [comment]
Wonder if this is my issue, I've had a plethora of issues over the weekend with massive instability, but since I've no way of identifying a culprit I haven't brought it to your attention. This sounds potentially in the same vein. Generations just stop working after awhile. I've disabled ALL extensions and it seems to help a little bit but ultimately, eventually, it will stop working.

**Comment by vladmandic** [comment]
updated to transformers 4.28.1

**Comment by BlackWyvern** [comment]
Transformers 4.26.1 (requirements.txt) and 4.28.1(as posted) exhibit the same issue.
Posting the startup environment info, in case it gives any insight.

```
13:48:03-071493 INFO     Starting SD.Next
13:48:03-092427 INFO     Python 3.10.6 on Windows
13:48:03-350737 INFO     Version: f6898c9a Fri May 5 13:40:53 2023 -0400
13:48:03-741693 INFO     Setting environment tuning
13:48:03-745682 INFO     nVidia CUDA toolkit detected
13:48:05-379334 INFO     Torch 2.0.0+cu118
13:48:05-397286 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
13:48:05-400261 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240 Arch (8, 6) Cores 68
```

![00012-2512420455-3d rendering of a small metal cube sitting on a glass table](https://user-images.githubusercontent.com/7834910/236566215-77c1caa9-656a-42ae-80b1-3555ec71f35c.jpg)

**Comment by BlackWyvern** [comment]
Unable to load using 4.19.2 now, due to somewhat recent changes. Loads, but still unable to generate using 4.26.1.
Referenced issues with Transformers to [HF: Transfomers](https://github.com/huggingface/transformers/issues/23238)

Requesting possible work-around.


`16:57:48-836833 INFO     Unloading xFormers
┌─────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────┐
│ I:\Opinionated Automatic\launch.py:149 in <module>                                                                              │
│                                                                                                                                 │
│   148                                                                                                                           │
│ > 149     instance = start_server(immediate=True, server=None)                                                                  │
│   150     while True:                                                                                                           │
│                                                                                                                                 │
│ I:\Opinionated Automatic\launch.py:121 in start_server                                                                          │
│                                                                                                                                 │
│   120     server = importlib.util.module_from_spec(module_spec)                                                                 │
│ > 121     module_spec.loader.exec_module(server)                                                                                │
│   122     if args.test:                                                                                                         │
│ in exec_module:883                                                                                                              │
│ in _call_with_frames_removed:241                                                                                                │
│                                                                                                                                 │
│ I:\Opinionated Automatic\webui.py:37 in <module>                                                                                │
│                                                                                                                                 │
│    36 import ldm.modules.encoders.modules # pylint: disable=W0611,C0411                                                         │
│ >  37 from modules import extra_networks, ui_extra_networks_checkpoints # pylint: disable=C041                                  │
│    38 from modules import extra_networks_hypernet, ui_extra_networks_hypernets, ui_extra_netwo                                  │
│                                                                                                                                 │
│ I:\Opinionated Automatic\modules\ui_extra_networks_checkpoints.py:5 in <module>                                                 │
│                                                                                                                                 │
│    4                                                                                                                            │
│ >  5 from modules import shared, ui_extra_networks, sd_models                                                                   │
│    6                                                                                                                            │
│                                                                                                                                 │
│ I:\Opinionated Automatic\modules\ui_extra_networks.py:10 in <module>                                                            │
│                                                                                                                                 │
│     9 from modules import shared                                                                                                │
│ >  10 from modules.images import read_info_from_image                                                                           │
│    11 from modules.generation_parameters_copypaste import image_from_url_text                                                   │
│                                                                                                                                 │
│ I:\Opinionated Automatic\modules\images.py:17 in <module>                                                                       │
│                                                                                                                                 │
│    16 from PIL import Image, ImageFont, ImageDraw, PngImagePlugin, ExifTags                                                     │
│ >  17 from modules import sd_samplers, shared, script_callbacks, errors, paths                                                  │
│    18                                                                                                                           │
│                                                                                                                                 │
│ I:\Opinionated Automatic\modules\sd_samplers.py:1 in <module>                                                                   │
│                                                                                                                                 │
│ >  1 from modules import sd_samplers_compvis, sd_samplers_kdiffusion, sd_samplers_diffusors,                                    │
│    2 from modules.sd_samplers_common import samples_to_image_grid, sample_to_image # pylint:                                    │
│                                                                                                                                 │
│ I:\Opinionated Automatic\modules\sd_samplers_diffusors.py:1 in <module>                                                         │
│                                                                                                                                 │
│ >  1 from diffusers import (                                                                                                    │
│    2     DDIMScheduler,                                                                                                         │
│                                                                                                                                 │
│ I:\Opinionated Automatic\venv\lib\site-packages\diffusers\__init__.py:28 in <module>                                            │
│                                                                                                                                 │
│    27 else:                                                                                                                     │
│ >  28     from .pipelines import OnnxRuntimeModel                                                                               │
│    29                                                                                                                           │
│                                                                                                                                 │
│ I:\Opinionated Automatic\venv\lib\site-packages\diffusers\pipelines\__init__.py:19 in <module>                                  │
│                                                                                                                                 │
│    18 else:                                                                                                                     │
│ >  19     from .dance_diffusion import DanceDiffusionPipeline                                                                   │
│    20     from .ddim import DDIMPipeline                                                                                        │
│                                                                                                                                 │
│ I:\Opinionated Automatic\venv\lib\site-packages\diffusers\pipelines\dance_diffusion\__init__.py:1 in <module>                   │
│                                                                                                                                 │
│ > 1 from .pipeline_dance_diffusion import DanceDiffusionPipeline                                                                │
│   2                                                                                                                             │
│                                                                                                                                 │
│ I:\Opinionated Automatic\venv\lib\site-packages\diffusers\pipelines\dance_diffusion\pipeline_dance_diffusion.py:21 in <module>  │
│                                                                                                                                 │
│    20 from ...utils import logging, randn_tensor                                                                                │
│ >  21 from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline                                                       │
│    22                                                                                                                           │
│                                                                                                                                 │
│ I:\Opinionated Automatic\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py:66 in <module>                            │
│                                                                                                                                 │
│     65     from transformers.utils import FLAX_WEIGHTS_NAME as TRANSFORMERS_FLAX_WEIGHTS_NAME                                   │
│ >   66     from transformers.utils import SAFE_WEIGHTS_NAME as TRANSFORMERS_SAFE_WEIGHTS_NAME                                   │
│     67     from transformers.utils import WEIGHTS_NAME as TRANSFORMERS_WEIGHTS_NAME                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils' (I:\Opinionated
Automatic\venv\lib\site-packages\transformers\utils\__init__.py)`

**Comment by vladmandic** [comment]
yes, need to combine with older diffusers. and since anyhow i cannot downgrade both in master this becomes somewhat of a moot point. i'm almost avoiding testing it not to be dissapointed ;)

**Comment by BlackWyvern** [comment]
Understandable. As this isn't really **_your_** issue, I'll roll back to my last known good version and lock it there.
