### ISSUE TITLE
 [Issue]: Launch.py is reset after updating the script

### ISSUE THREAD

**Issue by eyeweaver** [vladmandic/automatic#503]
### Issue Description

I've set the launch server arguments to check for updates with every launch.. but it seems that when the script is updated.. the Launch.py file is reset and the arguments are gone and I need to add them again..
am I doing something wrong?

**Comment by Gazzoo-byte** [comment]
I'm not certain if the arguments you're referring to are things like --medvram, if they are you can create a shortcut to webui.bat (if on windows) and add your arguments to that

![image](https://user-images.githubusercontent.com/73721238/234391110-93f31736-aa71-4982-a0ed-8c6091fa3fea.png)

However ensure to keep the shortcut outside of the 'automatic' folder, otherwise it gets removed during the upgrade process

**Comment by vladmandic** [comment]
@eyeweaver yes, you are. you're modifying file that is part of the repo. its normal it gets updated.
and in general, why not ask a question in discussions first instead of creating issue???
and yes, suggestion from @Gazzoo-byte is correct, thanks!
