### ISSUE TITLE
[Feature]: Add token merging (ToMe) parameters to x/y/z plot

### ISSUE THREAD

**Issue by nekoworkshop** [vladmandic/automatic#532]
### Feature description

Exposing the ToMe parameters (Master switch, hi-res only, merge ratio, etc) to the x/y/z plot.

I can work on this then open a PR if nobody is already working on it. Vlad already has enough on his plate.

### Version Platform Description

93b0de7e, Windows 11, Firefox.

**Comment by vladmandic** [comment]
I'd welcome the PR!

**Comment by Aptronymist** [comment]
> ### Feature description
> 
> Exposing the ToMe parameters (Master switch, hi-res only, merge ratio, etc) to the x/y/z plot.
> 
> I can work on this then open a PR if nobody is already working on it. Vlad already has enough on his plate.
> ### Version Platform Description
> 
> [93b0de7](https://github.com/vladmandic/automatic/commit/93b0de7e599453027ad7cab6266b42920ebc1250), Windows 11, Firefox.

I was going to post an issue for this, but since I see this... 
While you're in there, I should point out that token_merging_maximum_down_sampling is broken. If you try to change the value in the UI it has always frozen the interface for me, and required a reload.
This is partially due to https://github.com/vladmandic/automatic/blob/def7a02d82f4e7456177f3dbdf697dc7d02a3214/modules/generation_parameters_copypaste.py#L344 being a typo and not separating downsampling into two words. It's also not in the block of code above that, if it matters, even after changing those things on a local copy I couldn't get it to work, so I'm assuming more of it is broken.

I can of course just make a new issue for that if need be.

**Comment by nekoworkshop** [comment]
@Aptronymist As a workaround you can change this line https://github.com/vladmandic/automatic/blob/def7a02d82f4e7456177f3dbdf697dc7d02a3214/modules/shared.py#L457
to 
`"token_merging_maximum_down_sampling": OptionInfo(1, "Maximum down sampling", gr.Radio, lambda: {"choices": [1, 2, 4, 8]}),`

I have no idea why it hates the dropdown menu but at least the radio button works for me.

**Comment by Aptronymist** [comment]
> @Aptronymist As a workaround you can change this line https://github.com/vladmandic/automatic/blob/def7a02d82f4e7456177f3dbdf697dc7d02a3214/modules/shared.py#L457
> to 
> `"token_merging_maximum_down_sampling": OptionInfo(1, "Maximum down sampling", gr.Radio, lambda: {"choices": [1, 2, 4, 8]}),`
> 
> I have no idea why it hates the dropdown menu but at least the radio button works for me.

Nice, I'll do that. I did try doing that as a radio button as well, but perhaps I had mistakenly left other things changed so it still didn't work for me.

**Comment by nekoworkshop** [comment]
PR merged. Closing.
