### ISSUE TITLE
[Issue]: UI - Multidiffusion Upscaler Does Not Show on UI when Enabled

### ISSUE THREAD

**Issue by ilikenwf** [vladmandic/automatic#533]
### Issue Description

I installed this extension to try it out, and so far am having no luck with it showing up anywhere in the UI, so it is unusable.

**Comment by vladmandic** [comment]
In general, why not ask question in discussions first instead of opening an issue?
Multidiffusion upscaler is not a standard upscaler, it works completely differently and its part of the left column:

![image](https://user-images.githubusercontent.com/57876960/234691063-a931e858-41a6-4ea4-8ec6-d5003c1e22ae.png)

**Comment by ilikenwf** [comment]
It isn't appearing in the left column, either, if you mean below the preview window.

**Comment by ilikenwf** [comment]
[No console errors, but the checkbox is set in the extensions tab](https://github.com/vladmandic/automatic/discussions/534)
