### ISSUE TITLE
Not compatible with mov2mov extension

### ISSUE THREAD

**Issue by doodooextinction** [vladmandic/automatic#542]
### Issue Description

executing callback: E:\automatic\extensions\sd-webui-mov2mov\scripts\m2m_ui.py ui_tabs_callback: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ E:\automatic\modules\script_callbacks.py:142 in ui_tabs_callback                                                     │
│                                                                                                                      │
│   141 │   │   try:                                                                                                   │
│ ❱ 142 │   │   │   res += c.callback() or []                                                                          │
│   143 │   │   except Exception as e:                                                                                 │
│                                                                                                                      │
│ E:\automatic\extensions\sd-webui-mov2mov\scripts\m2m_ui.py:234 in on_ui_tabs                                         │
│                                                                                                                      │
│   233 │   │   │   │   │   │   │   res_switch_btn = ToolButton(value=switch_values_symbol, elem                       │
│ ❱ 234 │   │   │   │   │   │   │   if opts.dimensions_and_batch_together:                                             │
│   235 │   │   │   │   │   │   │   │   with gr.Column(elem_id=f"{id_part}_column_batch"):                             │
│                                                                                                                      │
│ E:\automatic\modules\shared.py:547 in __getattr__                                                                    │
│                                                                                                                      │
│   546 │   │                                                                                                          │
│ ❱ 547 │   │   return super(Options, self).__getattribute__(item)                                                     │
│   548                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Options' object has no attribute 'dimensions_and_batch_together'

### Version Platform Description

Version: 98adfb3151575f1020ecda509956ed9bef30ea86
used `git log` and it didn't show a date, and I don't remember when I installed it...

**Comment by vladmandic** [comment]
why would extension check value of deep internal variable that is used by core ui to perform one layout change???
but ok, i'll add compatibility option so extension does not complain. will be published in ~2h.

**Comment by alexopus** [comment]
I see this is closed. But I still get the exact same error with 1f6261b. Tried deleting and reinstalling mov2mov from scratch, but didn't help.

**Comment by vladmandic** [comment]
its the same error because i made a typo, just updated, sorry about that.

**Comment by alexopus** [comment]
Thanks, I updated.

Unfortunately, that was not the end of it:
```
executing callback: D:\automatic\extensions\sd-webui-mov2mov\scripts\m2m_ui.py ui_tabs_callback: UnboundLocalError
┌───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────┐
│ D:\automatic\modules\script_callbacks.py:142 in ui_tabs_callback                                                                                                                                     │
│                                                                                                                                                                                                      │
│   141 │   │   try:                                                                                                                                                                                   │
│ > 142 │   │   │   res += c.callback() or []                                                                                                                                                          │
│   143 │   │   except Exception as e:                                                                                                                                                                 │
│                                                                                                                                                                                                      │
│ D:\automatic\extensions\sd-webui-mov2mov\scripts\m2m_ui.py:323 in on_ui_tabs                                                                                                                         │
│                                                                                                                                                                                                      │
│   322 │   │   │   │   │   │                                                                                                                                                                          │
│ > 323 │   │   │   │   │   │      generate_mov_mode,                                                                                                                                                  │
│   324 │   │   │   │   │   │      noise_multiplier,                                                                                                                                                   │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
UnboundLocalError: local variable 'generate_mov_mode' referenced before assignment
```

**Comment by vladmandic** [comment]
ahhhh, more :)
i'm out for today, will take care of it tomorrow...reopening issue so i don't forget...

**Comment by doodooextinction** [comment]
> ahhhh, more :)
> i'm out for today, will take care of it tomorrow...reopening issue so i don't forget...

Service with a smile! What a trooper.

**Comment by jeffrey2212** [comment]
tried to copy from the org repo, with below line, seems working. 
    "dimensions_and_batch_together": OptionInfo(True, "Show Width/Height and Batch sliders in same row"),

**Comment by vladmandic** [comment]
yeah, but this is a bug in extension. it's totally valid that option is False and if its false, mov2mov does not create part of its UI, but later it does reference it unconditionally thus causing error `UnboundLocalError: local variable 'generate_mov_mode' referenced before assignment`.

i can set the variable to true by default, but a) settings are already written to `config.json`, so you'd need to delete it to reset all settings (as previous default was false), b) this only hides the issue in the extension, its not truly a fix. this should be reported to extension author.

**Comment by vladmandic** [comment]
@Evil-Dragon that is a totally different issue and WD 1.4 tagger extension has been flagged as pretty broken and needing a serious update - it references number of variables from core repo that are non existent for ages.
author fixed it in one place in january (see <https://github.com/toriato/stable-diffusion-webui-wd14-tagger/issues/36>), but not in this code where it still fails. report to extension author.

**Comment by DavG25** [comment]
Can you check if [this fork of mov2mov](https://github.com/DavG25/sd-webui-mov2mov) works for you?

I made a few changes that should hopefully solve most of the issues

**Comment by doodooextinction** [comment]
I’ll give’er a go later today.
Vlad fixed the visibility of the tab (thanks again btw), but it didn’t matter because the extension kept throwing errors. So, if you say you got an extension that works with Vlad’s Automatic, I’ll try it out.

**Comment by doodooextinction** [comment]
Okay, I couldn’t sleep, so I tried it. It works. Takes forever; might just be a me problem. One suggestion: can you output the images while it’s working instead of dumping them at the end? Or make a toggle for it. If this is going to take 3 hours for a 25 second clip, I need to be able to do some QA, at least in the beginning. I mean, the images don’t even dump if I interrupt.

Good Job! BTW. I’m not trying to sound ungrateful. I couldn’t do something like this. Just a wish list item.

**Comment by DavG25** [comment]
> Okay, I couldn’t sleep, so I tried it. It works. Takes forever; might just be a me problem. One suggestion: can you output the images while it’s working instead of dumping them at the end? Or make a toggle for it. If this is going to take 3 hours for a 25 second clip, I need to be able to do some QA, at least in the beginning. I mean, the images don’t even dump if I interrupt.

I plan to eventually add a similar feature, as for the speed it depends on the denoising strength just like img2img

**Comment by sebaxakerhtc** [comment]
> Can you check if [this fork of mov2mov](https://github.com/DavG25/sd-webui-mov2mov) works for you?
> 
> I made a few changes that should hopefully solve most of the issues

Worked. Thank you

**Comment by realenuf** [comment]
I can't get most extensions, including mov2mov to show up in SDnext or A1111. I tried both forks of mov2mov. I then installed a bunch of extensions from the list of those available, and only Dreambooth showed up in my tabs. I'm on Ubuntu 22.04.3.

**Comment by ktee95** [comment]
> Can you check if [this fork of mov2mov](https://github.com/DavG25/sd-webui-mov2mov) works for you?
> 
> I made a few changes that should hopefully solve most of the issues

I've tried your fork, but mov2mov tab just not show in UI

**Comment by realenuf** [comment]
I get this error message when I run webui.sh:
13:54:31-359575 ERROR    Module load:                                           
                         extensions/sd-webui-mov2mov/scripts/m2m_modnet.py:     
                         FileNotFoundError                                      
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /media/realenuf/BigDrive/sdnext/modules/script_loading.py:18 in load_module    │
│                                                                              │
│   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:       │
│ ❱ 18 │   │   │   module_spec.loader.exec_module(module)                      │
│   19 │   │   setup_logging() # reset since scripts can hijaack logging       │
│ in exec_module:883                                                           │
│ in _call_with_frames_removed:241                                             │
│                                                                              │
│ /media/realenuf/BigDrive/sdnext/extensions/sd-webui-mov2mov/scripts/m2m_modnet │
│ .py:21 in <module>                                                           │
│                                                                              │
│    20 modnet_models_path = ph.models_path + '/mov2mov-ModNet'                │
│ ❱  21 modnet_models = ['none'] + [model for model in os.listdir(modnet_model │
│    22                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 'models/mov2mov-ModNet'
13:54:31-692294 ERROR    Module load:                                           
                         extensions/sd-webui-mov2mov/scripts/m2m_ui.py:         
                         ImportError                                            
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /media/realenuf/BigDrive/sdnext/modules/script_loading.py:18 in load_module    │
│                                                                              │
│   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:       │
│ ❱ 18 │   │   │   module_spec.loader.exec_module(module)                      │
│   19 │   │   setup_logging() # reset since scripts can hijaack logging       │
│ in exec_module:883                                                           │
│ in _call_with_frames_removed:241                                             │
│                                                                              │
│ /media/realenuf/BigDrive/sdnext/extensions/sd-webui-mov2mov/scripts/m2m_ui.py: │
│ 10 in <module>                                                               │
│                                                                              │
│     9 from modules.call_queue import wrap_gradio_gpu_call                    │
│ ❱  10 from modules.sd_samplers import visible_sampler_names                  │
│    11 from modules.shared import opts                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'visible_sampler_names' from 
'modules.sd_samplers' (/media/realenuf/BigDrive/sdnext/modules/sd_samplers.py)
13:54:31-744837 ERROR    Module load:                                           
                         extensions/sd-webui-mov2mov/scripts/mov2mov.py:        
                         FileNotFoundError                                      
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /media/realenuf/BigDrive/sdnext/modules/script_loading.py:18 in load_module    │
│                                                                              │
│   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:       │
│ ❱ 18 │   │   │   module_spec.loader.exec_module(module)                      │
│   19 │   │   setup_logging() # reset since scripts can hijaack logging       │
│ in exec_module:883                                                           │
│ in _call_with_frames_removed:241                                             │
│                                                                              │
│ /media/realenuf/BigDrive/sdnext/extensions/sd-webui-mov2mov/scripts/mov2mov.py │
│ :17 in <module>                                                              │
│                                                                              │
│    16 from modules.ui import plaintext_to_html                               │
│ ❱  17 from scripts.m2m_modnet import get_model, infer, infer2                │
│    18                                                                        │
│                                                                              │
│ /media/realenuf/BigDrive/sdnext/extensions/sd-webui-mov2mov/scripts/m2m_modnet │
│ .py:21 in <module>                                                           │
│                                                                              │
│    20 modnet_models_path = ph.models_path + '/mov2mov-ModNet'                │
│ ❱  21 modnet_models = ['none'] + [model for model in os.listdir(modnet_model │
│    22                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 'models/mov2mov-ModNet'
