### ISSUE TITLE
[Issue]: Model changes automatically after image generation

### ISSUE THREAD

**Issue by pldsofficial** [vladmandic/automatic#554]
### Issue Description

After every image generation, undesired model change happens automatically.
This problem is not displayed on the ui itself, but it can be found on console.

In addition, I think there is a certain order of model changes but can't find the exact pattern.

### Version Platform Description

Version: 2023-04-26; Browser: Chrome latest; Theme: gradio/default

**Comment by vladmandic** [comment]
> This problem is not displayed on the ui itself, but it can be found on console.

If its displayed on console, please show that.

**Comment by econundrum** [comment]
This happens if you retrieve the settings from the last image when you press generate it also changes to the model used for that image. That may not be the issue here but it can be confusing if you don't realise one of the settings retrieved is actually the model.

I had this issue a couple of times on Automatic1111 before switching to this fork. But I'm assuming this behaves the same way.

**Comment by vladmandic** [comment]
there is an option to enable/disable that behavior in settings:
> When reading generation parameters from text into UI (from PNG info or pasted text), do not change the selected model/checkpoint.

**Comment by vladmandic** [comment]
@pldsofficial any updates?

**Comment by vladmandic** [comment]
closing as no updates other than initial report, will reopen if there is any new information.
