### ISSUE TITLE
[Issue]: CLI preview-embeddings.py \\ preview-models.py \\ grid.py

### ISSUE THREAD

**Issue by bparrott78** [vladmandic/automatic#595]
### Issue Description

When trying to use this from the command line, I get the issue:
Traceback (most recent call last):
  File "C:\automatic\cli\modules\preview-embeddings.py", line 16, in <module>
    from grid import grid
  File "C:\automatic\cli\modules\grid.py", line 11, in <module>
    import filetype
ModuleNotFoundError: No module named 'filetype'

webui is running, and benchmark accesses the api just fine.
It appears that the issue stems from grid.py...

### Version Platform Description

09:37:47-428483 INFO     Python 3.10.6 on Windows
09:37:47-929591 INFO     Version: bfe62127 Thu Apr 27 15:47:13 2023 -0400
09:37:51-773309 INFO     Upgraded to version: 57241e25 Fri Apr 28 09:28:59 2023 -0400

**Comment by vladmandic** [comment]
everything under /cli used to be my personal scripts, but now that repo has gained popularity, i need to make them far more modular.

but to answer your first question, scripts have additional requirements that are not installed by main setup since they are not needed by core repo.

to install those requirements, run `pip install -r requirements.txt` from `cli` folder
i'll track larger task to modularize cli scripts separately.

**Comment by bparrott78** [comment]
Did that, still got the same error, closed command line and re-opened, still didn't work.
pip installed filetype fixed it, but said it was using the cached version so idk, but it works now.

**Comment by vladmandic** [comment]
i just added `filetype` to requirements.txt few minutes ago :)
