### ISSUE TITLE
[Issue]: LoRa Block Weight Preset gets deleted after every upgrade

### ISSUE THREAD

**Issue by derspanier1** [vladmandic/automatic#658]
### Issue Description

Just as the title says, the preset for the weights gets reset after every upgrade. Not the end of the world, but a little bit annoying to fill it out every time.

### Version Platform Description

02:25:29-544317 INFO     Upgraded to version: dedd3ffa Sun Apr 30 20:08:44 2023 -0400

**Comment by vladmandic** [comment]
which exact preset are you talking about?

**Comment by derspanier1** [comment]
![image_2023-05-01_03-56-53](https://user-images.githubusercontent.com/117949621/235389955-c6ad6e29-f4df-4819-ad3e-19289726c8b1.png)
What i mean is: you can fill these 2 fields as seen on the screenshot with values. creating new block weight values that you can then apply to the loras. these values get pulled from a text file that sit in the scripts folder ( don´t ask me why ). After every upgrade, the added values get deleted.

**Comment by vladmandic** [comment]
i don't know which extension is that, but NO extension should store anything in core repo folders or modify any of its files. 

yes, i'm being more strict about it than original a1111, but it often leads to bad behavior that cannot be tracked down since such modifications persist even after extension is removed.

there is no reason why extension would not keep the file in its folder.

**Comment by derspanier1** [comment]
Yeah you are right, i shouldn´t even have raised this here. Will see if the extension author changes that. Thanks !
