### ISSUE TITLE
[Issue]: Error using Lora with img2img "expected all tensors to be on the same device"

### ISSUE THREAD

**Issue by NZperegrine** [vladmandic/automatic#723]
### Issue Description

Basically whenever I try to use Loras I get an error, works fine if I remove the Lora from the prompt, 
I upgraded a few times in the hope that would fix the error, before realizing removing the lora would allow me to continue. 
Before this error happened I was training an embedding, and while I've retraced my steps there, I may have missed something..

Apologies if gone about this the wrong, first timer. 
[error.txt](https://github.com/vladmandic/automatic/files/11379048/error.txt)

### Version Platform Description

Version: 530dafc4 Tue May 2 08:54:47 2023 -0400

Windows 10 22H2
arch: AMD64
cpu: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.10.9

device: NVIDIA GeForce RTX 3060 (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700

**Comment by TKS4** [comment]
I'd like to also comment this error might be a carryover from some older 1111 behavior. Even if you used:

set CUDA_VISIBLE_DEVICES=0

in the webuser.bat file, this error would still pop off, so there's clearly something being triggered by the inclusion of a Lora/LohA/Locon in the prompt that kicks off this error. The interesting part is, if you restart your session, and use the same exact prompt, there won't be this stall.

It's similar to periodic "Nan because of not enough precision" errors when you load up a specific VAE. If you actually restart the session, it goes away for some reason, even though no settings changes are made.

Though I haven't had this specific error ever since switching to vlad's UI, sorry I couldn't be of help. But I'd be curious to know if this is something you can reproduce, because I never could back when I was on the original repo.

**Comment by vladmandic** [comment]
i cannot reproduce. what are your settings -> cuda?

**Comment by Razunter** [comment]
Some recent change broke Lora for me too. With different error.
`RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same`
[config_log.zip](https://github.com/vladmandic/automatic/files/11383145/config_log.zip)

**Comment by vladmandic** [comment]
yes, that is a well known badly behaving extension. not only it doesn't work, it also copies its files into core repo, so you can't disable or uninstall it cleanly. no extension should ever touch files outside of its folder.

**Comment by FullBleed** [comment]
> yes, that is a well known badly behaving extension. not only it doesn't work, it also copies its files into core repo, so you can't disable or uninstall it cleanly. no extension should ever touch files outside of its folder.

I feel like we need a built-in "naughty list" to warn people about certain extensions...  And better guardrails to protect against such behavior.

**Comment by vladmandic** [comment]
yes, I agree. I'm actually planning to redesign extension manager from scratch, so this would be part of it.

**Comment by NZperegrine** [comment]
Correct you were, turning off the composable-lora extension brought things back to normal. 
And sorry for that late reply, think we might be in different time zones. :) thanks heaps for all you do.

**Comment by vladmandic** [comment]
Late reply is a week later, day or two is fine 😁
