### ISSUE TITLE
[Issue]: MAC M1

### ISSUE THREAD

**Issue by crazyfish2020** [vladmandic/automatic#810]
### Issue Description

(venv) (base) richard@60 automatic-master % ./webui.sh              
Create and activate python venv
Launching launch.py...
10:25:20-801975 INFO     Starting SD.Next                                       
10:25:20-804208 INFO     Python 3.10.9 on Darwin                                
10:25:20-841527 ERROR    Error running git: None / log -1 --pretty=format:"%h   
                         %ad"                                                   
10:25:20-842787 INFO     Version: 致命错误：您的当前分支 'main' 尚无任何提交    
10:25:20-852161 ERROR    Error running git: None / rev-parse HEAD               
10:25:21-255760 INFO     Latest published version:                              
                         22e588091376a458ae529d18c5ffaee5f0dcaa1b               
                         2023-05-06T12:51:23Z                                   
10:25:21-258200 INFO     Setting environment tuning                             
10:25:21-260243 INFO     Using CPU-only Torch                                   
10:25:22-373962 INFO     Torch 2.0.0                                            
10:25:22-374790 WARNING  Torch repoorts CUDA not available                      
10:25:22-375432 INFO     Installing package: tensorflow==2.12.0                 
10:25:28-817092 INFO     Verifying requirements                                 
10:25:28-841484 ERROR    Error running git: None / log -1 --pretty=format:"%at" 
10:25:28-843340 ERROR    Error getting local repository version: invalid literal
                         for int() with base 10: "致命错误：您的当前分支 'main' 
                         尚无任何提交"

**Comment by vladmandic** [comment]
you've provided no actual description, only log - that is not the correct way to create an isuse.
but ok. according to log this has nothing to do with M1 platform
all your github operations are failing. if you do not have github connectivity because its filtered by your country or organization, ask a question in discussions how to setup github proxy. 
closing as not a product issue - ask a question in discussions how to ensure github is available as this repo cannot work without github connectivity.
