### ISSUE TITLE
[Issue]: Enable upcast sampling doesn't work.

### ISSUE THREAD

**Issue by TomerGadol** [vladmandic/automatic#871]
### Issue Description

I have an NVIDIA 1660ti, up until the latest commit I could use "enable upcast sampling" to generate images that aren't black or return NaNs. After the latest update, this doesn't work and I'm required to enable `--no-half` for the model.
Also as of now, using upcast sampling instead of `--no-half`, my generation is more than 3 times slower.

I would rather use upcast sampling as it "Usually produces similar results to --no-half with better performance while using less memory".

After changing any settings, I restarted the server to test image generation with DPM ++2M Karras on 10 steps. No additional extensions are installed.

Other related settings:
Upcast cross attention layer to FP32 - enabled
Cross-attention optimization method - xFormers
Precision type - Autocast
Device precision type - FP16

### Version Platform Description

Version: 0f2a03a5 Thu May 11 11:50:51 2023 -0400
Win 10, Edge

**Comment by vladmandic** [comment]
latest versions run compatibility test on GPU with FP16 and automatically disable it if GPU does not return valid results.
the fact that you could run with only `--upcast-sampling` without corrupt images is mostly luck, but the underlying issue is that GPU is not working properly with FP16.

there are some reports that triggering "Enable cuDNN benchmark feature" nudges GPU in a right direction and then FP16 may actually work.

Other than that, I have too many reported issues and i want to be on a safe-side - if GPU does not perform FP16 ops correcty app now forces FP32 ops - and yes, that is much slower.
