### ISSUE TITLE
Windows and Mac Issues - READ FIRST

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#92]
### Issue Description

Currently `automatic.sh` installer and launcher script is Linux only.  
Old `webui.bat / webui.sh` scripts exist, but they do not have full functionality to install all submodules or even libraries.

The actual WebUI server does work on Windows/Mac, but requires advanced & manual installation.

New launcher/installer is on the way and I'll provide update here as soon as possible.
In the meantime, please do not create issues for Windows or Mac startup issues.

### Update

Major updated posted, see https://github.com/vladmandic/automatic/discussions/99 for details

**Comment by myndxero** [comment]
Godspeed, really looking forward to a contender to Auto that doesn't have us waiting forever for important updates.

I've seen a number of exciting things just sitting there and waiting for him to come around and approve.

**Comment by FutonGama** [comment]
Ah, that explains why I've been trying for 2 days without stopping to make it work and it wasn't working. Thanks for that information!!

**Comment by TomerGadol** [comment]
Honestly, after steps 1-3, I used `pip install -r requirements.txt pip install -r requirements_versions.txt` and then followed this [comment](https://github.com/vladmandic/automatic/issues/79#issuecomment-1501618893). Now everything is working as it should be.

**Comment by tcflying** [comment]
thanks for the work, so what the step if we are windows?

**Comment by tcflying** [comment]
venv "F:\stable-diffusion-webui\venv\Scripts\Python.exe"
Installing requirements for Web UI
Running extension installer: F:\stable-diffusion-webui\extensions\clip-interrogator-ext\install.py
A Installing requirements for CLIP Interrogator

Running extension installer: F:\stable-diffusion-webui\extensions\deforum-for-automatic1111-webui\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\ebsynth_utility\install.py
A current transparent-background 1.2.3

Running extension installer: F:\stable-diffusion-webui\extensions\PBRemTools\install.py
A Installing None
Installing onnxruntime-gpu...
Installing None
Installing opencv-python...
Installing None
Installing Pillow...
Installing None
Installing segmentation-refinement...
Installing None
Installing scikit-learn...

Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-3d-open-pose-editor\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-controlnet\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-nulienhance\install.py
A Installed.

Running extension installer: F:\stable-diffusion-webui\extensions\sd-webui-segment-anything\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py
A Stop Motion CN - Running Preload
Set Gradio Queue: True
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: 926ae204ef5de17efca2059c334b6098492a0641
Successfully installed fastapi-0.94.1 google-auth-oauthlib-0.4.6 tensorboard-2.12.0 transformers-4.26.1
[+] xformers version 0.0.17.dev464 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.18.0 installed.
[+] diffusers version 0.14.0 installed.
[+] transformers version 4.26.1 installed.
[+] bitsandbytes version 0.35.4 installed.

Running extension installer: F:\stable-diffusion-webui\extensions\stable-diffusion-webui-blip2-captioner\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\stable-diffusion-webui-rembg\install.py
Running extension installer: F:\stable-diffusion-webui\extensions\unprompted\install.py
A Installing requirements for Unprompted - img2pez
Installing requirements for Unprompted - pix2pix_zero

Running extension installer: F:\stable-diffusion-webui\extensions\video2video\install.py
A Installing video2video requirement: sk-video

Launching Web UI with arguments: --deepdanbooru --api --no-half-vae --opt-sdp-attention
F:\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: otobuf is an invalid version and will not be supported in a future release
  warnings.warn(
Stop Motion CN - Running Preload
Set Gradio Queue: True
Error running preload() for F:\stable-diffusion-webui\extensions-builtin\sd-webui-controlnet\preload.py
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\stable-diffusion-webui\modules\script_loading.py:28 in preload_extensions                                        │
│                                                                                                                     │
│   27             if hasattr(module, 'preload'):                                                                     │
│ > 28                 module.preload(parser)                                                                         │
│   29                                                                                                                │
│                                                                                                                     │
│ F:\stable-diffusion-webui\extensions-builtin\sd-webui-controlnet\preload.py:2 in preload                            │
│                                                                                                                     │
│   1 def preload(parser):                                                                                            │
│ > 2     parser.add_argument("--controlnet-dir", type=str, help="Path to directory with Contr                        │
│   3     parser.add_argument("--no-half-controlnet", action='store_true', help="do not switch                        │
│                                                                                                                     │
│                                               ... 4 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\argparse.py:1592 in _check_conflict              │
│                                                                                                                     │
│   1591             conflict_handler = self._get_handler()                                                           │
│ > 1592             conflict_handler(action, confl_optionals)                                                        │
│   1593                                                                                                              │
│                                                                                                                     │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\argparse.py:1601 in _handle_conflict_error       │
│                                                                                                                     │
│   1600                                      in conflicting_actions])                                                │
│ > 1601         raise ArgumentError(action, message % conflict_string)                                               │
│   1602                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ArgumentError: argument --controlnet-dir: conflicting option string: --controlnet-dir

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\stable-diffusion-webui\launch.py:311 in <module>                                                                 │
│                                                                                                                     │
│   310     prepare_environment()                                                                                     │
│ > 311     start()                                                                                                   │
│   312                                                                                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\launch.py:302 in start                                                                    │
│                                                                                                                     │
│   301     print(f"Launching {'API server' if '--nowebui' in sys.argv else 'Web UI'} with argum                      │
│ > 302     import webui                                                                                              │
│   303     if '--nowebui' in sys.argv:                                                                               │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\modules\shared.py:34 in <module>                                                          │
│                                                                                                                     │
│    33 script_loading.preload_extensions(extensions_dir, parser)                                                     │
│ >  34 script_loading.preload_extensions(extensions_builtin_dir, parser)                                             │
│    35                                                                                                               │
│                                                                                                                     │
│ F:\stable-diffusion-webui\modules\script_loading.py:32 in preload_extensions                                        │
│                                                                                                                     │
│   31             print(f"Error running preload() for {preload_script}", file=sys.stderr)                            │
│ > 32             shared.exception()                                                                                 │
│   33                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: partially initialized module 'modules.shared' has no attribute 'exception' (most likely due to a
circular import)
请按任意键继续. . .

**Comment by Aptronymist** [comment]
> ### Issue Description
> 
> Currently `automatic.sh` installer and launcher script is Linux only. Old `webui.bat / webui.sh` scripts exist, but they do not have full functionality to install all submodules or even libraries.

Sorry, Vlad, I feel like I opened the floodgates on you!

**Comment by vladmandic** [comment]
> Sorry, Vlad, I feel like I opened the floodgates on you!

LOL. Not blaming you :)

**Comment by vladmandic** [comment]
Major updated posted, see #99 for details

**Comment by myndxero** [comment]
Man I keep seeing updates notifications to my email. This really haa you
zoned in, eh? Appreciate your hard work. I've been dropping the link here
on Reddit. I can hold it off continuing until this is figured out.

**Comment by vladmandic** [comment]
Guys, I appreciate all community troubleshooting efforts!

I've just finished major update to installer/launcher as well as some environment auto-tunes.  
Hopefully now those steps should not be needed and should work out-of-the-box

Check [README](https://github.com/vladmandic/automatic#install) for updated notes

> git clone https://github.com/vladmandic/automatic SD

```log
Cloning into 'SD'...
remote: Enumerating objects: 20178, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 20178 (delta 5), reused 6 (delta 4), pack-reused 20157
Receiving objects: 100% (20178/20178), 30.22 MiB | 20.73 MiB/s, done.
Resolving deltas: 100% (14195/14195), done.
```

> webui.bat

```log
venv "D:\SD\venv\Scripts\Python.exe"
Python 3.11.3 on Windows
Running setup
Version: c830bbf7 Thu Apr 13 12:05:42 2023 -0400
Installing requirements
Installing packages
Error running pip with args: install --upgrade --no-deps xformers
Installing repositories
Installing submodules
Updating submodules
Built-in extensions: ['clip-interrogator-ext', 'LDSR', 'Lora', 'prompt-bracket-checker', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
Enabled extensions: []
Installing requirements
Setting environment tuning
Torch 2.0.0+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28
Server arguments: []
No module 'xformers'. Proceeding without it.
Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to D:\SD\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
100% | 3.97G/3.97G [02:47<00:00, 25.5MB/s]
Available models: 1
Image Browser: Creating database
Image Browser: Database created
Running on local URL:  http://127.0.0.1:7860
To create a public link, set `share=True` in `launch()`.
Checkpoint model.ckpt not found; loading fallback v1-5-pruned-emaonly.safetensors
Loading weights: D:\SD\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.3 GB -:--:--
Creating model from config: D:\SD\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Calculating sha256 for D:\SD\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors: 6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa
Applying scaled dot product cross attention optimization
Textual inversion embeddings loaded(0):
Model loaded in 4.9s (load=0.2s create=0.2s hash=2.8s apply=0.6s vae=0.4s move=0.6s)
Startup time: 186.4s (torch=6.3s libraries=4.2s models=167.3s codeformer=0.2s scripts=1.7s ui=1.4s gradio=0.1s checkpoint=5.2s)
```
