### ISSUE TITLE
[Feature]: Copy from Process Images to params.txt

### ISSUE THREAD

**Issue by AI-Casanova** [vladmandic/automatic#931]
### Feature description

I've been having a lot of trouble with sending images/parameters from Process Images to either the text or image tabs (eternal loading animation etc)

However, the button to read from params.txt (last generated image) always works for me.

Would it be feasible to add a button to Process Images to save the parameters to params.txt, so one could then tab over and load them (and the image separately if necessary)?

It's a workaround for sure, but it's been such a constant problem for all branches of the webUI, that until it gets solved 'correctly' might merit such a workaround.

**Comment by vladmandic** [comment]
i wanted to do a quick-fix, but this turned out to be a massive one - send-to buttons were not actually sending metadata to start with, only when image is loaded in processing then you get metadata. fixed that. 
plus added that params.txt is updated on each save, not just txt2img and img2img. so if you run processing, it will be updated and you can use restore button in txt2img.
