### ISSUE TITLE
[Issue]: Stylized progress bar for all samplers

### ISSUE THREAD

**Issue by diniamo** [vladmandic/automatic#935]
### Issue Description

The only sampler that has a stylized progress bar (console) is UniPC, and it's also the only one I could find the code of. If this is not something that anyone wants to work on, can I at least have a pointer as to where the progress bar logic is handled?

On an unrelated note, why is UniPC the default sampler in SD.Next? I couldn't find any information on that.

![image](https://github.com/vladmandic/automatic/assets/55629891/bb9b7ac7-3e61-4cfd-b15c-89aaa52a7089)
(top: UniPC, bottom: Euler a (or any other))

### Version Platform Description

Version: 926b8666
Arch Linux, Kitty terminal (also happens to my friend who uses Windows Terminal)

**Comment by vladmandic** [comment]
all other samplers come from external code, either `compvis` (ddim and plms) or `k-diffusers` (all others). modifying progress bar would be trivial, but that would mean that code would not be in sync with upstream and no automatic updates would be possible.

`unipc` is the only diffuser that is natively built inside this repo, so i can do those enhancements.
why is it default? because its not bad and its really fast. something has to be default, so why not `unipc`?

and why is this created as an issue? its a valid question, but far better suited for discussions.

**Comment by diniamo** [comment]
That's because I didn't know Github discussions existed, thank you for pointing that out as well as your answer.
