### ISSUE TITLE
[Issue]: startup stuck at Installing mmcv-full

### ISSUE THREAD

**Issue by SAC020** [vladmandic/automatic#968]
### Issue Description

Added a couple of extensions (addetailer, ddetailer) now I cannot start up webui as it gets stuck at Installing mmcv-full

Deleted the venv folder, same problem

I can give up on ddetailer (I _think_ that is causing the issue but don't know for sure) but since I cannot load webui I don't know how to eliminate it

Thank you

Clean setup.log attached

### Version Platform Description

Version: 8350b93a Mon May 15 09:32:20 2023 -0400

Windows 11

[setup.log](https://github.com/vladmandic/automatic/files/11479178/setup.log)

**Comment by vladmandic** [comment]
just delete its folder from `/extensions`
btw, it could be that its not "stuck", it just takes forever since `mmcv-full` is rarely available as binary and on most systems, it requires full rebuild from scratch. anyhow, i would not like any extension that requires such a heavy-weight component. even if it works, it would use soo much of your resources even when its idle.

**Comment by SAC020** [comment]
Thanks, it was the ddetailer extension. Deleted the folder, got rid of the issue
